/* $Id:  $   */
/* DO NOT EDIT - file generated by ObitTables.pl                      */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2008                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                        */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
#include "ObitTableSN.h"
#include "ObitTableList.h"
#include "ObitData.h"

/*----------------Obit:  Merx mollis mortibus nuper ------------------*/
/**
 * \file ObitTableSN.c
 * ObitTableSN class function definitions.
 *
 * This class is derived from the #ObitTable class.
 */

/** name of the class defined in this file */
static gchar *myClassName = "ObitTableSN";

/**  Function to obtain parent Table ClassInfo - ObitTable */
static ObitGetClassFP ObitParentGetClass = ObitTableGetClass;

/** name of the Row class defined in this file */
static gchar *myRowClassName = "ObitTableSNRow";

/**  Function to obtain parent TableRow ClassInfo */
static ObitGetClassFP ObitParentGetRowClass = ObitTableRowGetClass;

/*--------------- File Global Variables  ----------------*/
/*----------------  Table Row  ----------------------*/
/**
 * ClassInfo structure ObitTableClassInfo.
 * This structure is used by class objects to access class functions.
 */
static ObitTableSNRowClassInfo myRowClassInfo = {FALSE};

/*------------------  Table  ------------------------*/
/**
 * ClassInfo structure ObitTableSNClassInfo.
 * This structure is used by class objects to access class functions.
 */
static ObitTableSNClassInfo myClassInfo = {FALSE};

/*---------------Private function prototypes----------------*/
/** Private: Initialize newly instantiated Row object. */
void  ObitTableSNRowInit  (gpointer in);

/** Private: Deallocate Row members. */
void  ObitTableSNRowClear (gpointer in);

/** Private: Initialize newly instantiated object. */
void  ObitTableSNInit  (gpointer in);

/** Private: Deallocate members. */
void  ObitTableSNClear (gpointer in);

/** Private: update table specific info */
static void ObitTableSNUpdate (ObitTableSN *in, ObitErr *err);

/** Private: copy table keywords to descriptor info list */
static void ObitTableSNDumpKey (ObitTableSN *in, ObitErr *err);

/** Private: Set Class function pointers */
static void ObitTableSNClassInfoDefFn (gpointer inClass);

/** Private: Set Row Class function pointers */
static void ObitTableSNRowClassInfoDefFn (gpointer inClass);
/*----------------------Public functions---------------------------*/

/*------------------  Table Row ------------------------*/
/**
 * Constructor.
 * If table is open and for write, the row is attached to the buffer
 * Initializes Row class if needed on first call.
 * \param name An optional name for the object.
 * \return the new object.
 */
ObitTableSNRow* newObitTableSNRow (ObitTableSN *table)
{
  ObitTableSNRow* out;
  odouble   *dRow;
  oint      *iRow;
  gshort    *siRow;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;

  /* Class initialization if needed */
  if (!myRowClassInfo.initialized) ObitTableSNRowClassInit();

  /* allocate/init structure */
  out = g_malloc0(sizeof(ObitTableSNRow));

  /* initialize values */
  out->name = g_strdup("TableSN Row");

  /* set ClassInfo */
  out->ClassInfo = (gpointer)&myRowClassInfo;

  /* initialize other stuff */
  ObitTableSNRowInit((gpointer)out);
  out->myTable   = (ObitTable*)ObitTableRef((ObitTable*)table);

  /* If writing attach to buffer */
  if ((table->buffer) && (table->myDesc->access != OBIT_IO_ReadOnly) &&
      (table->myStatus != OBIT_Inactive)) {
    /* Typed pointers to row of data */  
    dRow  = (odouble*)table->buffer;
    iRow  = (oint*)table->buffer;
    siRow = (gshort*)table->buffer;
    fRow  = (ofloat*)table->buffer;
    cRow  = (gchar*)table->buffer;
    lRow  = (gboolean*)table->buffer;
    bRow  = (guint8*)table->buffer;
  
    /* Set row pointers to buffer */
    if (table->numPol>=1) out->MBDelay1 = fRow[table->MBDelay1Off];
    if (table->numPol>=1) out->Real1 = fRow + table->Real1Off;
    if (table->numPol>=1) out->Imag1 = fRow + table->Imag1Off;
    if (table->numPol>=1) out->Delay1 = fRow + table->Delay1Off;
    if (table->numPol>=1) out->Rate1 = fRow + table->Rate1Off;
    if (table->numPol>=1) out->Weight1 = fRow + table->Weight1Off;
    if (table->numPol>=1) out->RefAnt1 = iRow + table->RefAnt1Off;
    if (table->numPol>=2) out->MBDelay2 = fRow[table->MBDelay2Off];
    if (table->numPol>=2) out->Real2 = fRow + table->Real2Off;
    if (table->numPol>=2) out->Imag2 = fRow + table->Imag2Off;
    if (table->numPol>=2) out->Delay2 = fRow + table->Delay2Off;
    if (table->numPol>=2) out->Rate2 = fRow + table->Rate2Off;
    if (table->numPol>=2) out->Weight2 = fRow + table->Weight2Off;
    if (table->numPol>=2) out->RefAnt2 = iRow + table->RefAnt2Off;
  } /* end attaching row to table buffer */

 return out;
} /* end newObitTableSNRow */

/**
 * Returns ClassInfo pointer for the Row class.
 * \return pointer to the Row class structure.
 */
gconstpointer ObitTableSNRowGetClass (void)
{
  /* Class initialization if needed */
  if (!myRowClassInfo.initialized) ObitTableSNRowClassInit();
  return (gconstpointer)&myRowClassInfo;
} /* end ObitTableSNRowGetClass */

/*------------------  Table  ------------------------*/
/**
 * Constructor.
 * Initializes class if needed on first call.
 * \param name An optional name for the object.
 * \return the new object.
 */
ObitTableSN* newObitTableSN (gchar* name)
{
  ObitTableSN* out;

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableSNClassInit();

  /* allocate/init structure */
  out = g_malloc0(sizeof(ObitTableSN));

  /* initialize values */
  if (name!=NULL) out->name = g_strdup(name);
  else out->name = g_strdup("Noname");

  /* set ClassInfo */
  out->ClassInfo = (gpointer)&myClassInfo;

  /* initialize other stuff */
  ObitTableSNInit((gpointer)out);

 return out;
} /* end newObitTableSN */

/**
 * Returns ClassInfo pointer for the class.
 * \return pointer to the class structure.
 */
gconstpointer ObitTableSNGetClass (void)
{
  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableSNClassInit();

  return (gconstpointer)&myClassInfo;
} /* end ObitSNGetClass */

/**
 * Constructor from values.
 * Creates a new table structure and attaches to the TableList of file.
 * If the specified table already exists then it is returned.
 * Initializes class if needed on first call.
 * Forces an update of any disk resident structures (e.g. AIPS header).
 * \param name   An optional name for the object.
 * \param file   ObitData which which the table is to be associated.
 * \param ver    Table version number. 0=> add higher, value used returned
 * \param access access (OBIT_IO_ReadOnly, means do not create if it doesn't exist.
 * \param numPol The number of polarizations
 * \param numIF The number of IF
 * \param err Error stack, returns if not empty.
 * \return the new object, NULL on failure.
 */
ObitTableSN* newObitTableSNValue (gchar* name, ObitData *file, olong *ver,
 	                    ObitIOAccess access,
  		     oint numPol, oint numIF,
		     ObitErr *err)
{
  ObitTableSN* out=NULL;
  ObitTable *testTab=NULL;
  ObitTableDesc *desc=NULL;
  ObitTableList *list=NULL;
  ObitInfoList  *info=NULL;
  gboolean exist, optional;
  olong colNo, i, ncol, highVer;
  ObitIOCode retCode;
  gchar *tabType = "AIPS SN";
  gchar *routine = "newObitTableSNValue";

 /* error checks */
  g_assert(ObitErrIsA(err));
  if (err->error) return NULL;
  g_assert (ObitDataIsA(file));

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableSNClassInit();

  /* Check if the table already exists */
  /* Get TableList */
  list = ((ObitData*)file)->tableList;
  info = ((ObitData*)file)->info;

  /* Get highest version number if not specified */
  if (*ver==0) { 
    highVer = ObitTableListGetHigh (list, "AIPS SN");
    if (access==OBIT_IO_ReadOnly) *ver = highVer;
    else if (access==OBIT_IO_ReadWrite) *ver = highVer;
    else if (access==OBIT_IO_WriteOnly) *ver = highVer+1;
  }
  /* See if it already exists */
  exist = FALSE;
  if (*ver>0) { /* has to be specified */
    exist = ObitTableListGet(list, tabType, ver, &testTab, err);
    if (err->error) /* add traceback,return */
      Obit_traceback_val (err, routine,"", out);
  
    /* if readonly, it must exist to proceed */
    if ((access==OBIT_IO_ReadOnly) && !exist) return out;
    if (testTab!=NULL) { /* it exists, use it if is an ObitTableSN */
      if (ObitTableSNIsA(testTab)) { /* it is an ObitTableSN */
	out = ObitTableRef(testTab);
      } else { /* needs conversion */
 	out = ObitTableSNConvert(testTab);
	/* Update the TableList */
	ObitTableListPut(list, tabType, ver, (ObitTable*)out, err);
	if (err->error) /* add traceback,return */
	  Obit_traceback_val (err, routine,"", out);
      }
      testTab = ObitTableUnref(testTab); /* remove reference */
      return out; /* done */
    }
  } /* end of test for previously existing table */
  
  /* If access is ReadOnly make sure one exists */
  if (access==OBIT_IO_ReadOnly) { 
    highVer = ObitTableListGetHigh (list, "AIPS SN");
    if (highVer<=0) return out;
  }
  
  /* create basal table */
  testTab = newObitDataTable ((ObitData*)file, access, tabType,
			       ver, err);
  if (err->error) Obit_traceback_val (err, routine,"", out);
  
  /* likely need to convert */
  if (ObitTableSNIsA(testTab)) { 
    out = ObitTableRef(testTab);
  } else { /* needs conversion */
    out = ObitTableSNConvert(testTab);
  }
  testTab = ObitTableUnref(testTab); /* remove reference */

  /* Update the TableList */
  ObitTableListPut(list, tabType, ver, (ObitTable*)out, err);
  if (err->error) Obit_traceback_val (err, routine,"", out);

  /* if it previously existed merely return it */
  if (exist) return out; 

  /* set ClassInfo */
  out->ClassInfo = (gpointer)&myClassInfo;

  /* Set values */
  out->numPol = MAX (0, numPol);
  out->numIF = MAX (0, numIF);
  out->revision = 10;
  out->numNodes = 0;
  out->mGMod = 1.0;
  out->isApplied = FALSE;

  /* initialize descriptor */
  desc = out->myDesc;
  /* How many columns actually in table? */
  ncol = 8 + out->numPol*7 + out->numIF*0 ;
  desc->FieldName = g_malloc0((ncol+1)*sizeof(gchar*));
  desc->FieldUnit = g_malloc0((ncol+1)*sizeof(gchar*));
  desc->type      = g_malloc0((ncol+1)*sizeof(ObitInfoType));
  desc->dim       = g_malloc0((ncol+1)*sizeof(gint32*));
  for (i=0; i<ncol+1; i++) 
    desc->dim[i] = g_malloc0(MAXINFOELEMDIM*sizeof(gint32));

  desc->TableName = g_strdup(tabType);
  desc->sort[0] = 0;
  desc->sort[1] = 0;
  colNo = 0;

  /* Define Columns */
  desc->FieldName[colNo] = g_strdup("TIME    ");
  desc->FieldUnit[colNo] = g_strdup("DAYS");
  desc->type[colNo] = OBIT_double;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("TIME INTERVAL");
  desc->FieldUnit[colNo] = g_strdup("DAYS");
  desc->type[colNo] = OBIT_float;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("SOURCE ID");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_oint;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("ANTENNA NO.");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_oint;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("SUBARRAY");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_oint;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("FREQ ID");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_oint;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("I.FAR.ROT");
  desc->FieldUnit[colNo] = g_strdup("RAD/M**2");
  desc->type[colNo] = OBIT_float;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("NODE NO.");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_oint;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  if (numPol>=1) {
    desc->FieldName[colNo] = g_strdup("MBDELAY1");
    desc->FieldUnit[colNo] = g_strdup("SECONDS");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    colNo++;
  }
  if (numPol>=1) {
    desc->FieldName[colNo] = g_strdup("REAL1");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=1) {
    desc->FieldName[colNo] = g_strdup("IMAG1");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=1) {
    desc->FieldName[colNo] = g_strdup("DELAY 1");
    desc->FieldUnit[colNo] = g_strdup("SECONDS");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=1) {
    desc->FieldName[colNo] = g_strdup("RATE 1");
    desc->FieldUnit[colNo] = g_strdup("SEC/SEC");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=1) {
    desc->FieldName[colNo] = g_strdup("WEIGHT 1");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=1) {
    desc->FieldName[colNo] = g_strdup("REFANT 1");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_oint;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=2) {
    desc->FieldName[colNo] = g_strdup("MBDELAY2");
    desc->FieldUnit[colNo] = g_strdup("SECONDS");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    colNo++;
  }
  if (numPol>=2) {
    desc->FieldName[colNo] = g_strdup("REAL2");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=2) {
    desc->FieldName[colNo] = g_strdup("IMAG2");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=2) {
    desc->FieldName[colNo] = g_strdup("DELAY 2");
    desc->FieldUnit[colNo] = g_strdup("SECONDS");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=2) {
    desc->FieldName[colNo] = g_strdup("RATE 2");
    desc->FieldUnit[colNo] = g_strdup("SEC/SEC");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=2) {
    desc->FieldName[colNo] = g_strdup("WEIGHT 2");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_float;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  if (numPol>=2) {
    desc->FieldName[colNo] = g_strdup("REFANT 2");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_oint;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = numIF;
    colNo++;
  }
  /* Add _status column at end */
  desc->FieldName[colNo] = g_strdup("_status");
  desc->FieldUnit[colNo] = g_strdup("        ");
  desc->type[colNo] = OBIT_long;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  
  /* number of fields */
  desc->nfield = colNo + 1;

  /* initialize descriptor keywords */
  ObitTableSNDumpKey (out, err);
 
  /* index table descriptor */
  ObitTableDescIndex (desc);

  /* Open and Close to fully instantiate */
  retCode = ObitTableSNOpen(out, OBIT_IO_WriteOnly, err);
  if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
    Obit_traceback_val (err, routine, out->name, out);    
  
  retCode = ObitTableSNClose(out, err);
  if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
    Obit_traceback_val (err, routine, out->name, out); 

  /* Force update of disk resident info */
  retCode = ObitIOUpdateTables (((ObitData*)file)->myIO, info, err);
  if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
    Obit_traceback_val (err, routine, out->name, out); 
  
 return out;
} /* end newObitTableSNValue */

/**
 * Convert an ObitTable to an ObitTableSN.
 * New object will have references to members of in.
 * \param in  The object to copy, will still exist afterwards 
 *            and should be Unrefed if not needed.
 * \return pointer to the new object.
 */
ObitTableSN* ObitTableSNConvert (ObitTable* in)
{
  ObitTableSN *out;

  /* error check */
  g_assert(ObitTableIsA(in));

  /* create basic object */
  out = newObitTableSN(in->name);

  /* Delete structures on new */
  out->info   = ObitInfoListUnref(out->info);
  out->thread = ObitThreadUnref(out->thread);
  out->myDesc = ObitTableDescUnref(out->myDesc);
  out->mySel  = ObitTableSelUnref(out->mySel);
  
  /* Reference members of in */
  
  out->info   = ObitInfoListRef(in->info);
  out->thread = ObitThreadRef(in->thread);
  out->myDesc = ObitTableDescRef(in->myDesc);
  out->mySel  = ObitTableSelRef(in->mySel);

  /* Remember who I am */
 out->tabType = g_strdup(in->tabType);
 out->tabVer  = in->tabVer;
  /* Secret reference to host */ 
 out->myHost  = in->myHost;

  return out;
} /* end ObitTableSNConvert */


/**
 * Make a deep copy of input object.
 * Copies are made of complex members including disk files; these 
 * will be copied applying whatever selection is associated with the input.
 * Objects should be closed on input and will be closed on output.
 * In order for the disk file structures to be copied, the output file
 * must be sufficiently defined that it can be written.
 * The copy will be attempted but no errors will be logged until
 * both input and output have been successfully opened.
 * ObitInfoList and ObitThread members are only copied if the output object
 * didn't previously exist.
 * Parent class members are included but any derived class info is ignored.
 * \param in  The object to copy
 * \param out An existing object pointer for output or NULL if none exists.
 * \param err Error stack, returns if not empty.
 * \return pointer to the new object.
 */
ObitTableSN* ObitTableSNCopy (ObitTableSN *in, ObitTableSN *out, ObitErr *err)
{
  gchar *routine = "ObitTableSNCopy";

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableSNClassInit();

 /* error checks */
  g_assert(ObitErrIsA(err));
  if (err->error) return NULL;
  g_assert (ObitIsA(in, &myClassInfo));
  if (out) g_assert (ObitIsA(out, &myClassInfo));

  /* Use parent class to copy */
  out = (ObitTableSN*)ObitTableCopy ((ObitTable*)in, (ObitTable*)out, err);
  if (err->error) /* add traceback,return */
    Obit_traceback_val (err, routine,in->name, out);

  /* Copy this class  info */
  out->revision = in->revision;
  out->numPol = in->numPol;
  out->numIF = in->numIF;
  out->numAnt = in->numAnt;
  out->numNodes = in->numNodes;
  out->mGMod = in->mGMod;
  out->isApplied = in->isApplied;
  /* Update class specific info */
  ObitTableSNUpdate (out, err);
    
  return out;
} /* end ObitTableSNCopy */

/**
 * Initialize structures and open file.
 * The image descriptor is read if OBIT_IO_ReadOnly or 
 * OBIT_IO_ReadWrite and written to disk if opened OBIT_IO_WriteOnly.
 * After the file has been opened the member, buffer is initialized
 * for reading/storing the table unless member bufferSize is <0.
 * If the requested version ("Ver" in InfoList) is 0 then the highest
 * numbered table of the same type is opened on Read or Read/Write, 
 * or a new table is created on on Write.
 * The file etc. info should have been stored in the ObitInfoList:
 * \li "FileType" OBIT_long scalar = OBIT_IO_FITS or OBIT_IO_AIPS 
 *               for file type (see class documentation for details).
 * \li "nRowPIO" OBIT_long scalar = Maximum number of table rows
 *               per transfer, this is the target size for Reads (may be 
 *               fewer) and is used to create buffers.
 * \param in Pointer to object to be opened.
 * \param access access (OBIT_IO_ReadOnly,OBIT_IO_ReadWrite,
 *               or OBIT_IO_WriteOnly).
 *               If OBIT_IO_WriteOnly any existing data in the output file
 *               will be lost.
 * \param err ObitErr for reporting errors.
 * \return return code, OBIT_IO_OK=> OK
 */
ObitIOCode ObitTableSNOpen (ObitTableSN *in, ObitIOAccess access, 
			  ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  gint32 dim[MAXINFOELEMDIM] = {1,1,1,1,1};
  olong nRowPIO;
  gchar *routine = "ObitTableSNOpen";

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableSNClassInit();

  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA(in, &myClassInfo));

   /* Do one row at a time */
   nRowPIO = 1;
   ObitInfoListPut(in->info, "nRowPIO", OBIT_long, dim, (gconstpointer)&nRowPIO, err);
   if (err->error) /* add traceback,return */
     Obit_traceback_val (err, routine, in->name, retCode);
   
   /* use parent class open */
   retCode = ObitTableOpen ((ObitTable*)in, access, err);
   if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
     Obit_traceback_val (err, routine, in->name, retCode);
   
   /* Update class specific info */
   ObitTableSNUpdate (in, err);
   
   return retCode;
} /* end ObitTableSNOpen */

/**
 * Read a table row and return an easily digested version.
 * Scalar values are copied but for array values, pointers 
 * into the data array are returned.
 * \param in       Table to read
 * \param iSNRow   Row number, -1 -> next
 * \param row      Table Row structure to receive data
 * \param err ObitErr for reporting errors.
 * \return return code, OBIT_IO_OK=> OK
 */
ObitIOCode 
ObitTableSNReadRow  (ObitTableSN *in, olong iSNRow, ObitTableSNRow *row,
		     ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  odouble   *dRow;
  oint      *iRow;
  gshort    *siRow;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;
  gchar *routine = "ObitTableSNReadRow";
  
  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA(in, &myClassInfo));

  if (in->myStatus == OBIT_Inactive) {
    Obit_log_error(err, OBIT_Error,
		   "AIPS SN Table is inactive for  %s ", in->name);
    return retCode;
 }

  /* read row iSNRow */
  retCode = ObitTableRead ((ObitTable*)in, iSNRow, NULL,  err);
  if (err->error) 
    Obit_traceback_val (err, routine, in->name, retCode);

  /* Typed pointers to row of data */  
  dRow  = (odouble*)in->buffer;
  iRow  = (oint*)in->buffer;
  siRow = (gshort*)in->buffer;
  fRow  = (ofloat*)in->buffer;
  cRow  = (gchar*)in->buffer;
  lRow  = (gboolean*)in->buffer;
  bRow  = (guint8*)in->buffer;
  
  /* Copy scalar fields, for arrays only set pointer*/
  row->Time = dRow[in->TimeOff];
  row->TimeI = fRow[in->TimeIOff];
  row->SourID = iRow[in->SourIDOff];
  row->antNo = iRow[in->antNoOff];
  row->SubA = iRow[in->SubAOff];
  row->FreqID = iRow[in->FreqIDOff];
  row->IFR = fRow[in->IFROff];
  row->NodeNo = iRow[in->NodeNoOff];
  if (in->numPol>=1) row->MBDelay1 = fRow[in->MBDelay1Off];
  if (in->numPol>=1) row->Real1 = fRow + in->Real1Off;
  if (in->numPol>=1) row->Imag1 = fRow + in->Imag1Off;
  if (in->numPol>=1) row->Delay1 = fRow + in->Delay1Off;
  if (in->numPol>=1) row->Rate1 = fRow + in->Rate1Off;
  if (in->numPol>=1) row->Weight1 = fRow + in->Weight1Off;
  if (in->numPol>=1) row->RefAnt1 = iRow + in->RefAnt1Off;
  if (in->numPol>=2) row->MBDelay2 = fRow[in->MBDelay2Off];
  if (in->numPol>=2) row->Real2 = fRow + in->Real2Off;
  if (in->numPol>=2) row->Imag2 = fRow + in->Imag2Off;
  if (in->numPol>=2) row->Delay2 = fRow + in->Delay2Off;
  if (in->numPol>=2) row->Rate2 = fRow + in->Rate2Off;
  if (in->numPol>=2) row->Weight2 = fRow + in->Weight2Off;
  if (in->numPol>=2) row->RefAnt2 = iRow + in->RefAnt2Off;
  row->status = iRow[in->myDesc->statusOff];

  return retCode;
} /*  end ObitTableSNReadRow */

/**
 * Attach an ObitTableRow to the buffer of an ObitTable.
 * This is only useful prior to filling a row structure in preparation .
 * for a WriteRow operation.  Array members of the Row structure are .
 * pointers to independently allocated memory, this routine allows using .
 * the table IO buffer instead of allocating yet more memory..
 * This routine need only be called once to initialize a Row structure for write..
 * \param in  Table with buffer to be written 
 * \param row Table Row structure to attach 
 * \param err ObitErr for reporting errors.
 */
void 
ObitTableSNSetRow  (ObitTableSN *in, ObitTableSNRow *row,
		     ObitErr *err)
{
  odouble   *dRow;
  oint      *iRow;
  gshort    *siRow;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;
  
  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return;
  g_assert (ObitIsA(in, &myClassInfo));
  g_assert (ObitIsA(row, &myRowClassInfo));

  if (in->myStatus == OBIT_Inactive) {
    Obit_log_error(err, OBIT_Error,
		   "SN Table is inactive for  %s ", in->name);
    return;
 }

  /* Typed pointers to row of data */  
  dRow  = (odouble*)in->buffer;
  iRow  = (oint*)in->buffer;
  siRow = (gshort*)in->buffer;
  fRow  = (ofloat*)in->buffer;
  cRow  = (gchar*)in->buffer;
  lRow  = (gboolean*)in->buffer;
  bRow  = (guint8*)in->buffer;
  
  /* Set row pointers to buffer */
  if (in->numPol>=1) row->MBDelay1 = fRow[in->MBDelay1Off];
  if (in->numPol>=1) row->Real1 = fRow + in->Real1Off;
  if (in->numPol>=1) row->Imag1 = fRow + in->Imag1Off;
  if (in->numPol>=1) row->Delay1 = fRow + in->Delay1Off;
  if (in->numPol>=1) row->Rate1 = fRow + in->Rate1Off;
  if (in->numPol>=1) row->Weight1 = fRow + in->Weight1Off;
  if (in->numPol>=1) row->RefAnt1 = iRow + in->RefAnt1Off;
  if (in->numPol>=2) row->MBDelay2 = fRow[in->MBDelay2Off];
  if (in->numPol>=2) row->Real2 = fRow + in->Real2Off;
  if (in->numPol>=2) row->Imag2 = fRow + in->Imag2Off;
  if (in->numPol>=2) row->Delay2 = fRow + in->Delay2Off;
  if (in->numPol>=2) row->Rate2 = fRow + in->Rate2Off;
  if (in->numPol>=2) row->Weight2 = fRow + in->Weight2Off;
  if (in->numPol>=2) row->RefAnt2 = iRow + in->RefAnt2Off;

} /*  end ObitTableSNSetRow */

/**
 * Write a table row.
 * Before calling this routine, the row structure needs to be initialized
 * and filled with data. The array members of the row structure are  
 * pointers to independently allocated memory.  These pointers can be set to the 
 * correct table buffer locations using ObitTableSNSetRow  
 * \param in       Table to read
 * \param iSNRow   Row number, -1 -> next
 * \param row Table Row structure containing data
 * \param err ObitErr for reporting errors.
 * \return return code, OBIT_IO_OK=> OK
 */
ObitIOCode 
ObitTableSNWriteRow  (ObitTableSN *in, olong iSNRow, ObitTableSNRow *row,
		      ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  gshort    *siRow;
  odouble   *dRow;
  oint      *iRow, i;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;
  gchar *routine = "ObitTableSNWriteRow";
  

  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA(in, &myClassInfo));

  if (in->myStatus == OBIT_Inactive) {
    Obit_log_error(err, OBIT_Error,
		   "AIPS SN Table is inactive for %s ", in->name);
    return retCode;
 }

  /* Typed pointers to row of data */  
  dRow  = (odouble*)in->buffer;
  siRow = (gshort*)in->buffer;
  iRow  = (oint*)in->buffer;
  fRow  = (ofloat*)in->buffer;
  cRow  = (gchar*)in->buffer;
  lRow  = (gboolean*)in->buffer;
  bRow  = (guint8*)in->buffer;
  
  /* Make full copy of all data */
  dRow[in->TimeOff] = row->Time;
  fRow[in->TimeIOff] = row->TimeI;
  iRow[in->SourIDOff] = row->SourID;
  iRow[in->antNoOff] = row->antNo;
  iRow[in->SubAOff] = row->SubA;
  iRow[in->FreqIDOff] = row->FreqID;
  fRow[in->IFROff] = row->IFR;
  iRow[in->NodeNoOff] = row->NodeNo;
  if (in->numPol>=1) fRow[in->MBDelay1Off] = row->MBDelay1;
  if (in->numPol>=1)
    if (in->Real1Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Real1Col]; i++) 
        fRow[in->Real1Off+i] = row->Real1[i];
    } 
  if (in->numPol>=1)
    if (in->Imag1Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Imag1Col]; i++) 
        fRow[in->Imag1Off+i] = row->Imag1[i];
    } 
  if (in->numPol>=1)
    if (in->Delay1Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Delay1Col]; i++) 
        fRow[in->Delay1Off+i] = row->Delay1[i];
    } 
  if (in->numPol>=1)
    if (in->Rate1Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Rate1Col]; i++) 
        fRow[in->Rate1Off+i] = row->Rate1[i];
    } 
  if (in->numPol>=1)
    if (in->Weight1Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Weight1Col]; i++) 
        fRow[in->Weight1Off+i] = row->Weight1[i];
    } 
  if (in->numPol>=1)
    if (in->RefAnt1Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->RefAnt1Col]; i++) 
        iRow[in->RefAnt1Off+i] = row->RefAnt1[i];
    } 
  if (in->numPol>=2) fRow[in->MBDelay2Off] = row->MBDelay2;
  if (in->numPol>=2)
    if (in->Real2Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Real2Col]; i++) 
        fRow[in->Real2Off+i] = row->Real2[i];
    } 
  if (in->numPol>=2)
    if (in->Imag2Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Imag2Col]; i++) 
        fRow[in->Imag2Off+i] = row->Imag2[i];
    } 
  if (in->numPol>=2)
    if (in->Delay2Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Delay2Col]; i++) 
        fRow[in->Delay2Off+i] = row->Delay2[i];
    } 
  if (in->numPol>=2)
    if (in->Rate2Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Rate2Col]; i++) 
        fRow[in->Rate2Off+i] = row->Rate2[i];
    } 
  if (in->numPol>=2)
    if (in->Weight2Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->Weight2Col]; i++) 
        fRow[in->Weight2Off+i] = row->Weight2[i];
    } 
  if (in->numPol>=2)
    if (in->RefAnt2Col >= 0) { 
      for (i=0; i<in->myDesc->repeat[in->RefAnt2Col]; i++) 
        iRow[in->RefAnt2Off+i] = row->RefAnt2[i];
    } 

  /* copy status */
  iRow[in->myDesc->statusOff] = row->status;
   
  /* Write one row */
  in->myDesc->numRowBuff = 1;
 
  /* Write row iSNRow */
  retCode = ObitTableWrite ((ObitTable*)in, iSNRow, NULL,  err);
  if (err->error) 
    Obit_traceback_val (err, routine,in->name, retCode);

  return retCode;
} /*  end ObitTableSNWriteRow */

/**
 * Shutdown I/O.
 * \param in Pointer to object to be closed.
 * \param err ObitErr for reporting errors.
 * \return error code, OBIT_IO_OK=> OK
 */
ObitIOCode ObitTableSNClose (ObitTableSN *in, ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  gchar *routine = "ObitTableSNClose";

  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA((Obit*)in, &myClassInfo));
  /* Something going on? */
  if (in->myStatus == OBIT_Inactive) return OBIT_IO_OK;

  /* Update keywords on descriptor if not ReadOnly*/
  if (in->myDesc->access != OBIT_IO_ReadOnly) 
    ObitTableSNDumpKey (in, err);
  if (err->error) 
    Obit_traceback_val (err, routine, in->name, retCode);

  /* Close */
  retCode = ObitTableClose ((ObitTable*)in, err);
  if (err->error) 
    Obit_traceback_val (err, routine, in->name, retCode);

  return retCode;
} /* end ObitTableSNClose */

/*---------------Private functions--------------------------*/
/*----------------  TableSN Row  ----------------------*/
/**
 * Creates empty member objects, initialize reference count.
 * Parent classes portions are (recursively) initialized first
 * \param inn Pointer to the object to initialize.
 */
void ObitTableSNRowInit  (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableSNRow *in = inn;

  /* error checks */
  g_assert (in != NULL);

  /* recursively initialize parent class members */
  ParentClass = (ObitClassInfo*)(myRowClassInfo.ParentClass);
  if ((ParentClass!=NULL) && ( ParentClass->ObitInit!=NULL)) 
    ParentClass->ObitInit (inn);

  /* set members in this class */
  /* Set array members to NULL */
  in->Real1 = NULL;
  in->Imag1 = NULL;
  in->Delay1 = NULL;
  in->Rate1 = NULL;
  in->Weight1 = NULL;
  in->RefAnt1 = NULL;
  in->Real2 = NULL;
  in->Imag2 = NULL;
  in->Delay2 = NULL;
  in->Rate2 = NULL;
  in->Weight2 = NULL;
  in->RefAnt2 = NULL;

} /* end ObitTableSNRowInit */

/**
 * Deallocates member objects.
 * Does (recursive) deallocation of parent class members.
 * For some reason this wasn't build into the GType class.
 * \param  inn Pointer to the object to deallocate.
 *           Actually it should be an ObitTableSNRow* cast to an Obit*.
 */
void ObitTableSNRowClear (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableSNRow *in = inn;

  /* error checks */
  g_assert (ObitIsA(in, &myRowClassInfo));

  /* delete this class members */
  /* Do not free data array pointers as they were not malloced */
  
  /* unlink parent class members */
  ParentClass = (ObitClassInfo*)(myRowClassInfo.ParentClass);
  /* delete parent class members */
  if ((ParentClass!=NULL) && ( ParentClass->ObitClear!=NULL)) 
    ParentClass->ObitClear (inn);
  
} /* end ObitTableSNRowClear */

/**
 * Initialize global ClassInfo Structure.
 */
void ObitTableSNRowClassInit (void)
{
  if (myRowClassInfo.initialized) return;  /* only once */
  
  /* Set name and parent for this class */
  myRowClassInfo.ClassName   = g_strdup(myRowClassName);
  myRowClassInfo.ParentClass = ObitParentGetRowClass();

  /* Set function pointers */
  ObitTableSNRowClassInfoDefFn ((gpointer)&myRowClassInfo);
 
  myRowClassInfo.initialized = TRUE; /* Now initialized */
 
} /* end ObitTableSNRowClassInit */

/**
 * Initialize global ClassInfo Function pointers.
 */
static void ObitTableSNRowClassInfoDefFn (gpointer inClass)
{
  ObitTableSNRowClassInfo *theClass = (ObitTableSNRowClassInfo*)inClass;
  ObitClassInfo *ParentClass = (ObitClassInfo*)myRowClassInfo.ParentClass;

  if (theClass->initialized) return;  /* only once */

  /* Check type of inClass */
  g_assert (ObitInfoIsA(inClass, (ObitClassInfo*)&myRowClassInfo));

  /* Initialize (recursively) parent class first */
  if ((ParentClass!=NULL) && 
      (ParentClass->ObitClassInfoDefFn!=NULL))
    ParentClass->ObitClassInfoDefFn(theClass);

  /* function pointers defined or overloaded this class */
  theClass->ObitClassInit = (ObitClassInitFP)ObitTableSNRowClassInit;
  theClass->ObitClassInfoDefFn = (ObitClassInfoDefFnFP)ObitTableSNRowClassInfoDefFn;
  theClass->ObitGetClass  = (ObitGetClassFP)ObitTableSNRowGetClass;
  theClass->newObit         = NULL;
  theClass->newObitTableRow = (newObitTableRowFP)newObitTableSNRow;
  theClass->ObitCopy        = NULL;
  theClass->ObitClone       = NULL;
  theClass->ObitClear       = (ObitClearFP)ObitTableSNRowClear;
  theClass->ObitInit        = (ObitInitFP)ObitTableSNRowInit;

} /* end ObitTableSNRowClassDefFn */

/*------------------  TableSN  ------------------------*/

/**
 * Creates empty member objects, initialize reference count.
 * Parent classes portions are (recursively) initialized first
 * \param inn Pointer to the object to initialize.
 */
void ObitTableSNInit  (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableSN *in = inn;

  /* error checks */
  g_assert (in != NULL);

  /* recursively initialize parent class members */
  ParentClass = (ObitClassInfo*)(myClassInfo.ParentClass);
  if ((ParentClass!=NULL) && ( ParentClass->ObitInit!=NULL)) 
    ParentClass->ObitInit (inn);

  /* set members in this class */

} /* end ObitTableSNInit */

/**
 * Deallocates member objects.
 * Does (recursive) deallocation of parent class members.
 * For some reason this wasn't build into the GType class.
 * \param  inn Pointer to the object to deallocate.
 *           Actually it should be an ObitTableSN* cast to an Obit*.
 */
void ObitTableSNClear (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableSN *in = inn;

  /* error checks */
  g_assert (ObitIsA(in, &myClassInfo));

  /* delete this class members */
  
  /* unlink parent class members */
  ParentClass = (ObitClassInfo*)(myClassInfo.ParentClass);
  /* delete parent class members */
  if ((ParentClass!=NULL) && ( ParentClass->ObitClear!=NULL)) 
    ParentClass->ObitClear (inn);
  
} /* end ObitTableSNClear */

/**
 * Initialize global ClassInfo Structure.
 */
void ObitTableSNClassInit (void)
{
  if (myClassInfo.initialized) return;  /* only once */
  
  /* Set name and parent for this class */
  myClassInfo.ClassName   = g_strdup(myClassName);
  myClassInfo.ParentClass = ObitParentGetClass();

  /* Set function pointers */
  ObitTableSNClassInfoDefFn ((gpointer)&myClassInfo);
 
  myClassInfo.initialized = TRUE; /* Now initialized */
 
} /* end ObitTableSNClassInit */

/**
 * Initialize global ClassInfo Function pointers.
 */
static void ObitTableSNClassInfoDefFn (gpointer inClass)
{
  ObitTableSNClassInfo *theClass = (ObitTableSNClassInfo*)inClass;
  ObitClassInfo *ParentClass = (ObitClassInfo*)myClassInfo.ParentClass;

  if (theClass->initialized) return;  /* only once */

  /* Check type of inClass */
  g_assert (ObitInfoIsA(inClass, (ObitClassInfo*)&myClassInfo));

  /* Initialize (recursively) parent class first */
  if ((ParentClass!=NULL) && 
      (ParentClass->ObitClassInfoDefFn!=NULL))
    ParentClass->ObitClassInfoDefFn(theClass);

  /* function pointers defined or overloaded this class */
  theClass->ObitClassInit = (ObitClassInitFP)ObitTableSNClassInit;
  theClass->ObitClassInfoDefFn = (ObitClassInfoDefFnFP)ObitTableSNClassInfoDefFn;
  theClass->ObitGetClass  = (ObitGetClassFP)ObitTableSNGetClass;
  theClass->newObit       = (newObitFP)newObitTableSN;
  theClass->ObitCopy      = (ObitCopyFP)ObitTableSNCopy;
  theClass->ObitClone     = (ObitCloneFP)ObitTableClone;
  theClass->ObitClear     = (ObitClearFP)ObitTableSNClear;
  theClass->ObitInit      = (ObitInitFP)ObitTableSNInit;
  theClass->ObitTableConvert = (ObitTableConvertFP)ObitTableSNConvert;
  theClass->ObitTableOpen    = (ObitTableOpenFP)ObitTableSNOpen;
  theClass->ObitTableClose   = (ObitTableCloseFP)ObitTableSNClose;
  theClass->ObitTableRead    = (ObitTableReadFP)ObitTableRead;
  theClass->ObitTableReadSelect = 
    (ObitTableReadSelectFP)ObitTableReadSelect;
  theClass->ObitTableWrite = (ObitTableWriteFP)ObitTableWrite;
  theClass->ObitTableReadRow = 
    (ObitTableReadRowFP)ObitTableSNReadRow;
  theClass->ObitTableWriteRow = 
    (ObitTableWriteRowFP)ObitTableSNWriteRow;

} /* end ObitTableSNClassDefFn */

/**
 * Get table specific information from the infolist or descriptor
 * \param info Table to update
 * \param err  ObitErr for reporting errors.
 */
static void ObitTableSNUpdate (ObitTableSN *in, ObitErr *err)
{
  olong i;
  ObitInfoType type;
  gint32 dim[MAXINFOELEMDIM];
  ObitTableDesc *desc;
   union ObitInfoListEquiv InfoReal; 

 /* error checks */
   g_assert(ObitErrIsA(err));
  if (err->error) return;
  g_assert (ObitIsA(in, &myClassInfo));

  /* Get Keywords */
   /* revision */
  in->revision = 10; 
  ObitInfoListGetTest(in->myDesc->info, "REVISION", &type, dim, 
		       (gpointer)&in->revision);
   /* numPol */
  if (!ObitInfoListGet(in->myDesc->info, "NO_POL", &type, dim, 
		       (gpointer)&in->numPol, err)) return;
   /* numIF */
  if (!ObitInfoListGet(in->myDesc->info, "NO_IF", &type, dim, 
		       (gpointer)&in->numIF, err)) return;
   /* numAnt */
  if (!ObitInfoListGet(in->myDesc->info, "NO_ANT", &type, dim, 
		       (gpointer)&in->numAnt, err)) return;
   /* numNodes */
  in->numNodes = 0; 
  ObitInfoListGetTest(in->myDesc->info, "NO_NODES", &type, dim, 
		       (gpointer)&in->numNodes);
  in->mGMod = 1.0; 
  InfoReal.dbl = 1.0; 
  type = OBIT_double;
  ObitInfoListGetTest(in->myDesc->info, "MGMOD", &type, dim, 
		       (gpointer)&InfoReal);
  if (type==OBIT_double) in->mGMod = InfoReal.dbl;
  if (type==OBIT_float)  in->mGMod = InfoReal.flt;
   /* isApplied */
  in->isApplied = FALSE; 
  ObitInfoListGetTest(in->myDesc->info, "APPLIED", &type, dim, 
		       (gpointer)&in->isApplied);

  /* initialize column numbers/offsets */
  in->TimeOff = -1;
  in->TimeCol = -1;
  in->TimeIOff = -1;
  in->TimeICol = -1;
  in->SourIDOff = -1;
  in->SourIDCol = -1;
  in->antNoOff = -1;
  in->antNoCol = -1;
  in->SubAOff = -1;
  in->SubACol = -1;
  in->FreqIDOff = -1;
  in->FreqIDCol = -1;
  in->IFROff = -1;
  in->IFRCol = -1;
  in->NodeNoOff = -1;
  in->NodeNoCol = -1;
  in->MBDelay1Off = -1;
  in->MBDelay1Col = -1;
  in->Real1Off = -1;
  in->Real1Col = -1;
  in->Imag1Off = -1;
  in->Imag1Col = -1;
  in->Delay1Off = -1;
  in->Delay1Col = -1;
  in->Rate1Off = -1;
  in->Rate1Col = -1;
  in->Weight1Off = -1;
  in->Weight1Col = -1;
  in->RefAnt1Off = -1;
  in->RefAnt1Col = -1;
  in->MBDelay2Off = -1;
  in->MBDelay2Col = -1;
  in->Real2Off = -1;
  in->Real2Col = -1;
  in->Imag2Off = -1;
  in->Imag2Col = -1;
  in->Delay2Off = -1;
  in->Delay2Col = -1;
  in->Rate2Off = -1;
  in->Rate2Col = -1;
  in->Weight2Off = -1;
  in->Weight2Col = -1;
  in->RefAnt2Off = -1;
  in->RefAnt2Col = -1;
  /* Find columns and set offsets */
  desc = in->myDesc;
  if (desc->FieldName) {
    for (i=0; i<desc->nfield; i++) {
      if (!strncmp (desc->FieldName[i], "TIME    ", 8)) {
	 in->TimeOff = desc->offset[i];
 	 in->TimeCol = i;
      }
      if (!strncmp (desc->FieldName[i], "TIME INTERVAL", 13)) {
	 in->TimeIOff = desc->offset[i];
 	 in->TimeICol = i;
      }
      if (!strncmp (desc->FieldName[i], "SOURCE ID", 9)) {
	 in->SourIDOff = desc->offset[i];
 	 in->SourIDCol = i;
      }
      if (!strncmp (desc->FieldName[i], "ANTENNA NO.", 11)) {
	 in->antNoOff = desc->offset[i];
 	 in->antNoCol = i;
      }
      if (!strncmp (desc->FieldName[i], "SUBARRAY", 8)) {
	 in->SubAOff = desc->offset[i];
 	 in->SubACol = i;
      }
      if (!strncmp (desc->FieldName[i], "FREQ ID", 7)) {
	 in->FreqIDOff = desc->offset[i];
 	 in->FreqIDCol = i;
      }
      if (!strncmp (desc->FieldName[i], "I.FAR.ROT", 9)) {
	 in->IFROff = desc->offset[i];
 	 in->IFRCol = i;
      }
      if (!strncmp (desc->FieldName[i], "NODE NO.", 8)) {
	 in->NodeNoOff = desc->offset[i];
 	 in->NodeNoCol = i;
      }
      if (!strncmp (desc->FieldName[i], "MBDELAY1", 8)) {
	     in->MBDelay1Off = desc->offset[i];
 	     in->MBDelay1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "REAL1", 5)) {
	     in->Real1Off = desc->offset[i];
 	     in->Real1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "IMAG1", 5)) {
	     in->Imag1Off = desc->offset[i];
 	     in->Imag1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "DELAY 1", 7)) {
	     in->Delay1Off = desc->offset[i];
 	     in->Delay1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "RATE 1", 6)) {
	     in->Rate1Off = desc->offset[i];
 	     in->Rate1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "WEIGHT 1", 8)) {
	     in->Weight1Off = desc->offset[i];
 	     in->Weight1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "REFANT 1", 8)) {
	     in->RefAnt1Off = desc->offset[i];
 	     in->RefAnt1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "MBDELAY2", 8)) {
	     in->MBDelay2Off = desc->offset[i];
 	     in->MBDelay2Col = i;
      }
      if (!strncmp (desc->FieldName[i], "REAL2", 5)) {
	     in->Real2Off = desc->offset[i];
 	     in->Real2Col = i;
      }
      if (!strncmp (desc->FieldName[i], "IMAG2", 5)) {
	     in->Imag2Off = desc->offset[i];
 	     in->Imag2Col = i;
      }
      if (!strncmp (desc->FieldName[i], "DELAY 2", 7)) {
	     in->Delay2Off = desc->offset[i];
 	     in->Delay2Col = i;
      }
      if (!strncmp (desc->FieldName[i], "RATE 2", 6)) {
	     in->Rate2Off = desc->offset[i];
 	     in->Rate2Col = i;
      }
      if (!strncmp (desc->FieldName[i], "WEIGHT 2", 8)) {
	     in->Weight2Off = desc->offset[i];
 	     in->Weight2Col = i;
      }
      if (!strncmp (desc->FieldName[i], "REFANT 2", 8)) {
	     in->RefAnt2Off = desc->offset[i];
 	     in->RefAnt2Col = i;
      }
     }
  }

  /* Check required columns */
  Obit_return_if_fail((in->TimeOff > -1), err,
       "ObitTableSNUpdate: Could not find column Time");
  Obit_return_if_fail((in->TimeIOff > -1), err,
       "ObitTableSNUpdate: Could not find column TimeI");
  Obit_return_if_fail((in->SourIDOff > -1), err,
       "ObitTableSNUpdate: Could not find column SourID");
  Obit_return_if_fail((in->antNoOff > -1), err,
       "ObitTableSNUpdate: Could not find column antNo");
  Obit_return_if_fail((in->SubAOff > -1), err,
       "ObitTableSNUpdate: Could not find column SubA");
  Obit_return_if_fail((in->FreqIDOff > -1), err,
       "ObitTableSNUpdate: Could not find column FreqID");
  Obit_return_if_fail((in->IFROff > -1), err,
       "ObitTableSNUpdate: Could not find column IFR");
  Obit_return_if_fail((in->NodeNoOff > -1), err,
       "ObitTableSNUpdate: Could not find column NodeNo");
  if (in->numPol>=1) {
    Obit_return_if_fail((in->MBDelay1Off > -1), err,
       "ObitTableSNUpdate: Could not find column MBDelay1");
    Obit_return_if_fail((in->Real1Off > -1), err,
       "ObitTableSNUpdate: Could not find column Real1");
    Obit_return_if_fail((in->Imag1Off > -1), err,
       "ObitTableSNUpdate: Could not find column Imag1");
    Obit_return_if_fail((in->Delay1Off > -1), err,
       "ObitTableSNUpdate: Could not find column Delay1");
    Obit_return_if_fail((in->Rate1Off > -1), err,
       "ObitTableSNUpdate: Could not find column Rate1");
    Obit_return_if_fail((in->Weight1Off > -1), err,
       "ObitTableSNUpdate: Could not find column Weight1");
  } /* end of if index in range */
  if (in->numPol>=2) {
    Obit_return_if_fail((in->MBDelay2Off > -1), err,
       "ObitTableSNUpdate: Could not find column MBDelay2");
    Obit_return_if_fail((in->Real2Off > -1), err,
       "ObitTableSNUpdate: Could not find column Real2");
    Obit_return_if_fail((in->Imag2Off > -1), err,
       "ObitTableSNUpdate: Could not find column Imag2");
    Obit_return_if_fail((in->Delay2Off > -1), err,
       "ObitTableSNUpdate: Could not find column Delay2");
    Obit_return_if_fail((in->Rate2Off > -1), err,
       "ObitTableSNUpdate: Could not find column Rate2");
    Obit_return_if_fail((in->Weight2Off > -1), err,
       "ObitTableSNUpdate: Could not find column Weight2");
  } /* end of if index in range */
} /* end ObitTableSNUpdate */

/**
 * Copy table specific (keyword) information  to infolist.
 * \param info Table to update
 * \param err  ObitErr for reporting errors.
 */
static void ObitTableSNDumpKey (ObitTableSN *in, ObitErr *err)
{
  ObitInfoList *info=NULL;
  ObitInfoType type;
  gint32 dim[MAXINFOELEMDIM] = {1,1,1,1,1};

 /* error checks */
   g_assert(ObitErrIsA(err));
  if (err->error) return;
  g_assert (ObitIsA(in, &myClassInfo));

  /* Set Keywords */
  if (in->myIO!=NULL) info = ((ObitTableDesc*)(in->myIO->myDesc))->info;
  else info = in->myDesc->info;
  /* revision */
  type  = OBIT_oint;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "REVISION", type, dim, 
		  (gpointer)&in->revision);
  /* numPol */
  type  = OBIT_oint;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "NO_POL", type, dim, 
		  (gpointer)&in->numPol);
  /* numIF */
  type  = OBIT_oint;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "NO_IF", type, dim, 
		  (gpointer)&in->numIF);
  /* numAnt */
  type  = OBIT_oint;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "NO_ANT", type, dim, 
		  (gpointer)&in->numAnt);
  /* numNodes */
  type  = OBIT_oint;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "NO_NODES", type, dim, 
		  (gpointer)&in->numNodes);
  /* mGMod */
  type  = OBIT_double;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "MGMOD", type, dim, 
		  (gpointer)&in->mGMod);
  /* isApplied */
  type  = OBIT_bool;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "APPLIED", type, dim, 
		  (gpointer)&in->isApplied);
   
} /* end ObitTableSNDumpKey */
