/* $Id:  $  */
/* DO NOT EDIT - file generated by ObitSDTables.pl                    */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2008                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                        */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
/*  Define the basic components of the ObitTableOTFArrayGeom  structure          */
/*  This is intended to be included in a class structure definition   */
/**
 * \file ObitTableOTFArrayGeomDef.h
 * ObitTableOTFArrayGeom structure members for derived classes.
 */
#include "ObitTableDef.h"  /* Parent class definitions */
/** Telescope X coordinate. (meters, earth center) */
gdouble  TeleX;
/** Telescope Y coordinate. (meters, earth center) */
gdouble  TeleY;
/** Telescope Z coordinate. (meters, earth center) */
gdouble  TeleZ;
/** Reference date as "YYYYMMDD" */
gchar  RefDate[MAXKEYCHARTABLEOTFArrayGeom];
/** Earth rotation rate (deg/IAT day) */
gdouble  DegDay;
/** Polar position X (meters) on ref. date */
gfloat  PolarX;
/** Polar position Y (meters) on ref. date */
gfloat  PolarY;
/** GST at time=0 (degrees) on the reference date */
gdouble  GSTiat0;
/** UT1-UTC  (time sec.) */
gfloat  ut1Utc;
/** data time-UTC  (time sec.) */
gfloat  dataUtc;
/** IAT - UTC (sec). */
gfloat  iatUtc;
/** Time system, 'IAT' or 'UTC' */
gchar  TimeSys[MAXKEYCHARTABLEOTFArrayGeom];
/** Column offset for Detector number in table record */
olong  detectorOff;
/** Physical column number for Detector number in table record */
olong  detectorCol;
/** Column offset for ``Azimuth'' offset from nominal pointing, this is formally ``cros in table record */
olong  azOffOff;
/** Physical column number for ``Azimuth'' offset from nominal pointing, this is formally ``cros in table record */
olong  azOffCol;
/** Column offset for Elevation offset from nominal pointing in table record */
olong  elOffOff;
/** Physical column number for Elevation offset from nominal pointing in table record */
olong  elOffCol;
