/* $Id$  */
/* DO NOT EDIT - file generated by ObitSDTables.pl                    */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2009                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                        */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
#ifndef ObitTableGBTPARSENSOR_H 
#define ObitTableGBTPARSENSOR_H 

#include "Obit.h"
#include "ObitErr.h"
#include "ObitTable.h"
#include "ObitData.h"

/*-------- Obit: Merx mollis mortibus nuper ------------------*/
/**
 * \file ObitTableGBTPARSENSOR.h
 * ObitTableGBTPARSENSOR class definition.
 *
 * Table in GBT archive/PAR file.
 * This class contains tabular data and allows access.
 * This class is derived from the ObitTable class. 
 *
 * This class contains tabular data and allows access.
 * ObitTableGBTPARSENSOR" 
 * An ObitTableGBTPARSENSOR is the front end to a persistent disk resident structure.
 * This class is derived from the ObitTable class.
 *
 * \section TableDataStorage Table data storage
 * In memory tables are stored in a fashion similar to how they are 
 * stored on disk - in large blocks in memory rather than structures.
 * Due to the word alignment requirements of some machines, they are 
 * stored by order of the decreasing element size: 
 * double, float long, int, short, char rather than the logical order.
 * The details of the storage in the buffer are kept in the 
 * #ObitTableGBTPARSENSORDesc.
 *
 * In addition to the normal tabular data, a table will have a "_status"
 * column to indicate the status of each row.
 * The status value is read from and written to (some modification) AIPS 
 * tables but are not written to externally generated FITS tables which
 * don't have these colummns.  It will be written to Obit generated tables
 * which will have these columns.
 * Status values:
 * \li status = 0 => normal
 * \li status = 1 => row has been modified (or created) and needs to be
 *                   written.
 * \li status = -1 => row has been marked invalid.
 *
 * \section ObitTableGBTPARSENSORSpecification Specifying desired data transfer parameters
 * The desired data transfers are specified in the member ObitInfoList.
 * There are separate sets of parameters used to specify the FITS 
 * data files.
 * In the following an ObitInfoList entry is defined by 
 * the name in double quotes, the data type code as an #ObitInfoType enum 
 * and the dimensions of the array (? => depends on application).
 * To specify whether the underlying data files are FITS
 * \li "FileType" OBIT_int (1,1,1) OBIT_IO_FITS 
 * which are values of an #ObitIOType enum defined in ObitIO.h.
 *
 * The following apply to both types of files:
 * \li "nRowPIO", OBIT_int, Max. Number of visibilities per 
 *     "Read" or "Write" operation.  Default = 1.
 *
 * \subsection TableFITS FITS files
 * This implementation uses cfitsio which allows using, in addition to 
 * regular FITS images, gzip compressed files, pipes, shared memory 
 * and a number of other input forms.
 * The convenience Macro #ObitTableGBTPARSENSORSetFITS simplifies specifying the 
 * desired data.
 * Binary tables are used for storing visibility data in FITS.
 * For accessing FITS files the following entries in the ObitInfoList 
 * are used:
 * \li "FileName" OBIT_string (?,1,1) FITS file name.
 * \li "TabName"  OBIT_string (?,1,1) Table name (e.g. "AIPS CC").
 * \li "Ver"      OBIT_int    (1,1,1) Table version number
 *
 *
 * \section ObitTableGBTPARSENSORaccess Creators and Destructors
 * An ObitTableGBTPARSENSOR can be created using newObitTableGBTPARSENSORValue which attaches the 
 * table to an ObitData for the object.  
 * If the output ObitTableGBTPARSENSOR has previously been specified, including file information,
 * then ObitTableGBTPARSENSORCopy will copy the disk resident as well as the memory 
 * resident information.
 *
 * A copy of a pointer to an ObitTableGBTPARSENSOR should always be made using the
 * ObitTableGBTPARSENSORRef function which updates the reference count in the object.
 * Then whenever freeing an ObitTableGBTPARSENSOR or changing a pointer, the function
 * ObitTableGBTPARSENSORUnref will decrement the reference count and destroy the object
 * when the reference count hits 0.
 *
 * \section ObitTableGBTPARSENSORUsage I/O
 * Visibility data is available after an input object is "Opened"
 * and "Read".
 * I/O optionally uses a buffer attached to the ObitTableGBTPARSENSOR or some external
 * location.
 * To Write an ObitTableGBTPARSENSOR, create it, open it, and write.
 * The object should be closed to ensure all data is flushed to disk.
 * Deletion of an ObitTableGBTPARSENSOR after its final unreferencing will automatically
 * close it.
 */

/*--------------Class definitions-------------------------------------*/

/** Number of characters for Table keyword */
 #define MAXKEYCHARTABLESensor 24

/** ObitTableGBTPARSENSOR Class structure. */
typedef struct {
#include "ObitTableGBTPARSENSORDef.h"   /* this class definition */
} ObitTableGBTPARSENSOR;

/** ObitTableGBTPARSENSORRow Class structure. */
typedef struct {
#include "ObitTableGBTPARSENSORRowDef.h"   /* this class row definition */
} ObitTableGBTPARSENSORRow;

/*----------------- Macroes ---------------------------*/
/** 
 * Macro to unreference (and possibly destroy) an ObitTableGBTPARSENSOR
 * returns an ObitTableGBTPARSENSOR*.
 * in = object to unreference
 */
#define ObitTableGBTPARSENSORUnref(in) ObitUnref (in)

/** 
 * Macro to reference (update reference count) an ObitTableGBTPARSENSOR.
 * returns an ObitTableGBTPARSENSOR*.
 * in = object to reference
 */
#define ObitTableGBTPARSENSORRef(in) ObitRef (in)

/** 
 * Macro to determine if an object is the member of this or a 
 * derived class.
 * Returns TRUE if a member, else FALSE
 * in = object to reference
 */
#define ObitTableGBTPARSENSORIsA(in) ObitIsA (in, ObitTableGBTPARSENSORGetClass())

/** 
 * Macro to unreference (and possibly destroy) an ObitTableGBTPARSENSORRow
 * returns an ObitTableGBTPARSENSORRow*.
 * in = object to unreference
 */
#define ObitTableGBTPARSENSORRowUnref(in) ObitUnref (in)

/** 
 * Macro to reference (update reference count) an ObitTableGBTPARSENSORRow.
 * returns an ObitTableGBTPARSENSORRow*.
 * in = object to reference
 */
#define ObitTableGBTPARSENSORRowRef(in) ObitRef (in)

/** 
 * Macro to determine if an object is the member of this or a 
 * derived class.
 * Returns TRUE if a member, else FALSE
 * in = object to reference
 */
#define ObitTableGBTPARSENSORRowIsA(in) ObitIsA (in, ObitTableGBTPARSENSORRowGetClass())

/*---------------Public functions---------------------------*/
/*----------------Table Row Functions ----------------------*/
/** Public: Row Class initializer. */
void ObitTableGBTPARSENSORRowClassInit (void);

/** Public: Constructor. */
ObitTableGBTPARSENSORRow* newObitTableGBTPARSENSORRow (ObitTableGBTPARSENSOR *table);

/** Public: ClassInfo pointer */
gconstpointer ObitTableGBTPARSENSORRowGetClass (void);

/*------------------Table Functions ------------------------*/
/** Public: Class initializer. */
void ObitTableGBTPARSENSORClassInit (void);

/** Public: Constructor. */
ObitTableGBTPARSENSOR* newObitTableGBTPARSENSOR (gchar* name);

/** Public: Constructor from values. */
ObitTableGBTPARSENSOR* 
newObitTableGBTPARSENSORValue (gchar* name, ObitData *file, olong *ver,
  		     ObitIOAccess access,
                    
		     ObitErr *err);

/** Public: ClassInfo pointer */
gconstpointer ObitTableGBTPARSENSORGetClass (void);

/** Public: Copy (deep) constructor. */
ObitTableGBTPARSENSOR* ObitTableGBTPARSENSORCopy  (ObitTableGBTPARSENSOR *in, ObitTableGBTPARSENSOR *out, 
			   ObitErr *err);

/** Public: Copy (shallow) constructor. */
ObitTableGBTPARSENSOR* ObitTableGBTPARSENSORClone (ObitTableGBTPARSENSOR *in, ObitTableGBTPARSENSOR *out);

/** Public: Convert an ObitTable to an ObitTableGBTPARSENSOR */
ObitTableGBTPARSENSOR* ObitTableGBTPARSENSORConvert  (ObitTable *in);

/** Public: Create ObitIO structures and open file */
ObitIOCode ObitTableGBTPARSENSOROpen (ObitTableGBTPARSENSOR *in, ObitIOAccess access, 
			  ObitErr *err);

/** Public: Read a table row */
ObitIOCode 
ObitTableGBTPARSENSORReadRow  (ObitTableGBTPARSENSOR *in, olong iSensorRow, ObitTableGBTPARSENSORRow *row,
		     ObitErr *err);

/** Public: Init a table row for write */
void 
ObitTableGBTPARSENSORSetRow  (ObitTableGBTPARSENSOR *in, ObitTableGBTPARSENSORRow *row,
		     ObitErr *err);

/** Public: Write a table row */
ObitIOCode 
ObitTableGBTPARSENSORWriteRow  (ObitTableGBTPARSENSOR *in, olong iSensorRow, ObitTableGBTPARSENSORRow *row,
		     ObitErr *err);

/** Public: Close file and become inactive */
ObitIOCode ObitTableGBTPARSENSORClose (ObitTableGBTPARSENSOR *in, ObitErr *err);

/*----------- ClassInfo Structure -----------------------------------*/
/**
 * ClassInfo Structure.
 * Contains class name, a pointer to any parent class
 * (NULL if none) and function pointers.
 */
typedef struct  {
#include "ObitTableGBTPARSENSORClassDef.h"
} ObitTableGBTPARSENSORClassInfo; 

/**
 * ClassInfo Structure For TableObitTableGBTPARSENSORRow.
 * Contains class name, a pointer to any parent class
 * (NULL if none) and function pointers.
 */
typedef struct  {
#include "ObitTableGBTPARSENSORRowClassDef.h"
} ObitTableGBTPARSENSORRowClassInfo; 
#endif /* ObitTableGBTPARSENSOR_H */ 
