/* $Id$  */
/* DO NOT EDIT - file generated by ObitSDTables.pl                    */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2008                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                        */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
/*  Define the basic components of the ObitTableGBTANTPOSPF  structure          */
/*  This is intended to be included in a class structure definition   */
/**
 * \file ObitTableGBTANTPOSPFDef.h
 * ObitTableGBTANTPOSPF structure members for derived classes.
 */
#include "ObitTableDef.h"  /* Parent class definitions */
/** Column offset for  in table record */
olong  dmjdOff;
/** Physical column number for  in table record */
olong  dmjdCol;
/** Column offset for  in table record */
olong  raj2000Off;
/** Physical column number for  in table record */
olong  raj2000Col;
/** Column offset for  in table record */
olong  decj2000Off;
/** Physical column number for  in table record */
olong  decj2000Col;
/** Column offset for  in table record */
olong  mntAazOff;
/** Physical column number for  in table record */
olong  mntAazCol;
/** Column offset for  in table record */
olong  mntElOff;
/** Physical column number for  in table record */
olong  mntElCol;
/** Column offset for  in table record */
olong  refractOff;
/** Physical column number for  in table record */
olong  refractCol;
/** Column offset for  in table record */
olong  majorOff;
/** Physical column number for  in table record */
olong  majorCol;
/** Column offset for  in table record */
olong  minorOff;
/** Physical column number for  in table record */
olong  minorCol;
/** Column offset for Prime focus focus. in table record */
olong  pfFocusOff;
/** Physical column number for Prime focus focus. in table record */
olong  pfFocusCol;
/** Column offset for Prime focus rotation in table record */
olong  pfRotationOff;
/** Physical column number for Prime focus rotation in table record */
olong  pfRotationCol;
/** Column offset for  in table record */
olong  pfXOff;
/** Physical column number for  in table record */
olong  pfXCol;
