/* $Id:  $  */
/* DO NOT EDIT - file generated by ObitSDTables.pl                    */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2008                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                        */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
/*  Define the basic components of the ObitTableOTFCal  structure          */
/*  This is intended to be included in a class structure definition   */
/**
 * \file ObitTableOTFCalDef.h
 * ObitTableOTFCal structure members for derived classes.
 */
#include "ObitTableDef.h"  /* Parent class definitions */
/** Number of detectors) */
oint  numDet;
/** Number of polynomial coefficients describing atmospheric emission */
oint  numPoly;
/** Column offset for The center time. in table record */
olong  TimeOff;
/** Physical column number for The center time. in table record */
olong  TimeCol;
/** Column offset for The integration time. in table record */
olong  TimeIOff;
/** Physical column number for The integration time. in table record */
olong  TimeICol;
/** Column offset for Celestial target, as index in target table. in table record */
olong  TargetOff;
/** Physical column number for Celestial target, as index in target table. in table record */
olong  TargetCol;
/** Column offset for Correction to the ``Azimuth'' for all detectors in table record */
olong  dAzOff;
/** Physical column number for Correction to the ``Azimuth'' for all detectors in table record */
olong  dAzCol;
/** Column offset for Correction to the Elevation for all detectors. in table record */
olong  dElOff;
/** Physical column number for Correction to the Elevation for all detectors. in table record */
olong  dElCol;
/** Column offset for Cal value in units of raw data per detector, to be subtracted fro in table record */
olong  calOff;
/** Physical column number for Cal value in units of raw data per detector, to be subtracted fro in table record */
olong  calCol;
/** Column offset for Additive (subtractive actually) term per detector in table record */
olong  addOff;
/** Physical column number for Additive (subtractive actually) term per detector in table record */
olong  addCol;
/** Column offset for Additive (subtractive actually) term per detector in table record */
olong  multOff;
/** Physical column number for Additive (subtractive actually) term per detector in table record */
olong  multCol;
/** Column offset for Weight value per detector in table record */
olong  wtOff;
/** Physical column number for Weight value per detector in table record */
olong  wtCol;
/** Column offset for Polynomial atmosphere model, expansion in RA, dec about pointing position in table record */
olong  polyOff;
/** Physical column number for Polynomial atmosphere model, expansion in RA, dec about pointing position in table record */
olong  polyCol;
