/* $Id$  */
/* DO NOT EDIT - file generated by ObitSDTables.pl                    */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2013                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                        */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
#include "ObitTableGBTVEGASSAMPLER.h"
#include "ObitTableList.h"
#include "ObitData.h"

/*----------------Obit: Merx mollis mortibus nuperS ------------------*/
/**
 * \file ObitTableGBTVEGASSAMPLER.c
 * ObitTableGBTVEGASSAMPLER class function definitions.
 * This class is derived from the ObitTable class.
 */

/** name of the class defined in this file */
static gchar *myClassName = "ObitTableGBTVEGASSAMPLER";

/**  Function to obtain parent Table ClassInfo - ObitTable */
static ObitGetClassFP ObitParentGetClass = ObitTableGetClass;

/** name of the Row class defined in this file */
static gchar *myRowClassName = "ObitTableGBTVEGASSAMPLERRow";

/**  Function to obtain parent TableRow ClassInfo */
static ObitGetClassFP ObitParentGetRowClass = ObitTableRowGetClass;

/*--------------- File Global Variables  ----------------*/
/*----------------  Table Row  ----------------------*/
/**
 * ClassInfo structure ObitTableClassInfo.
 * This structure is used by class objects to access class functions.
 */
static ObitTableGBTVEGASSAMPLERRowClassInfo myRowClassInfo = {FALSE};

/*------------------  Table  ------------------------*/
/**
 * ClassInfo structure ObitTableGBTVEGASSAMPLERClassInfo.
 * This structure is used by class objects to access class functions.
 */
static ObitTableGBTVEGASSAMPLERClassInfo myClassInfo = {FALSE};


/*---------------Private function prototypes----------------*/
/** Private: Initialize newly instantiated Row object. */
void  ObitTableGBTVEGASSAMPLERRowInit  (gpointer in);

/** Private: Deallocate Row members. */
void  ObitTableGBTVEGASSAMPLERRowClear (gpointer in);

/** Private: Initialize newly instantiated object. */
void  ObitTableGBTVEGASSAMPLERInit  (gpointer in);

/** Private: Deallocate members. */
void  ObitTableGBTVEGASSAMPLERClear (gpointer in);

/** Private: update table specific info */
static void ObitTableGBTVEGASSAMPLERUpdate (ObitTableGBTVEGASSAMPLER *in, ObitErr *err);

/** Private: copy table keywords to descriptor info list */
static void ObitTableGBTVEGASSAMPLERDumpKey (ObitTableGBTVEGASSAMPLER *in, ObitErr *err);

/** Private: Set Class function pointers */
static void ObitTableGBTVEGASSAMPLERClassInfoDefFn (gpointer inClass);

/** Private: Set Row Class function pointers */
static void ObitTableGBTVEGASSAMPLERRowClassInfoDefFn (gpointer inClass);
/*----------------------Public functions---------------------------*/

/*------------------  Table Row ------------------------*/
/**
 * Constructor.
 * If table is open and for write, the row is attached to the buffer
 * Initializes Row class if needed on first call.
 * \param name An optional name for the object.
 * \return the new object.
 */
ObitTableGBTVEGASSAMPLERRow* newObitTableGBTVEGASSAMPLERRow (ObitTableGBTVEGASSAMPLER *table)
{
  ObitTableGBTVEGASSAMPLERRow* out;
  odouble   *dRow;
  oint      *iRow;
  ollong    *llRow;
  gshort    *siRow;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;

  /* Class initialization if needed */
  if (!myRowClassInfo.initialized) ObitTableGBTVEGASSAMPLERRowClassInit();

  /* allocate/init structure */
  out = g_malloc0(sizeof(ObitTableGBTVEGASSAMPLERRow));

  /* initialize values */
  out->name = g_strdup("TableObitTableGBTVEGASSAMPLER Row");

  /* set ClassInfo */
  out->ClassInfo = (gpointer)&myRowClassInfo;

  /* initialize other stuff */
  ObitTableGBTVEGASSAMPLERRowInit((gpointer)out);
  out->myTable   = (ObitTable*)ObitTableRef((ObitTable*)table);

  /* If writing attach to buffer */
  if ((table->buffer) && (table->myDesc->access != OBIT_IO_ReadOnly) &&
      (table->myStatus != OBIT_Inactive)) {
    /* Typed pointers to row of data */  
    dRow  = (odouble*)table->buffer;
    iRow  = (oint*)table->buffer;
    siRow = (gshort*)table->buffer;
    llRow = (ollong*)table->buffer;
    fRow  = (ofloat*)table->buffer;
    cRow  = (gchar*)table->buffer;
    lRow  = (gboolean*)table->buffer;
    bRow  = (guint8*)table->buffer;
  
    /* Set row pointers to buffer */
    out->datatype = cRow + table->datatypeOff;
  } /* end attaching row to table buffer */

 return out;
} /* end newObitTablePORTRow */

/**
 * Returns ClassInfo pointer for the Row class.
 * \return pointer to the Row class structure.
 */
gconstpointer ObitTableGBTVEGASSAMPLERRowGetClass (void)
{
  /* Class initialization if needed */
  if (!myRowClassInfo.initialized) ObitTableGBTVEGASSAMPLERRowClassInit();
  return (gconstpointer)&myRowClassInfo;
} /* end ObitTableGBTVEGASSAMPLERRowGetClass */

/*------------------  Table  ------------------------*/
/**
 * Constructor.
 * Initializes class if needed on first call.
 * \param name An optional name for the object.
 * \return the new object.
 */
ObitTableGBTVEGASSAMPLER* newObitTableGBTVEGASSAMPLER (gchar* name)
{
  ObitTableGBTVEGASSAMPLER* out;

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableGBTVEGASSAMPLERClassInit();

  /* allocate/init structure */
  out = g_malloc0(sizeof(ObitTableGBTVEGASSAMPLER));

  /* initialize values */
  if (name!=NULL) out->name = g_strdup(name);
  else out->name = g_strdup("Noname");

  /* set ClassInfo */
  out->ClassInfo = (gpointer)&myClassInfo;

  /* initialize other stuff */
  ObitTableGBTVEGASSAMPLERInit((gpointer)out);

 return out;
} /* end newObitTableGBTVEGASSAMPLER */

/**
 * Returns ClassInfo pointer for the class.
 * \return pointer to the class structure.
 */
gconstpointer ObitTableGBTVEGASSAMPLERGetClass (void)
{
  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableGBTVEGASSAMPLERClassInit();
  return (gconstpointer)&myClassInfo;
} /* end ObitTableGBTVEGASSAMPLERGetClass */

/**
 * Constructor from values.
 * Creates a new table structure and attaches to the TableList of file.
 * If the specified table already exists then it is returned.
 * Initializes class if needed on first call.
 * Forces an update of any disk resident structures (e.g. AIPS header).
 * \param name   An optional name for the object.
 * \param file   ObitData which which the table is to be associated.
 * \param ver    Table version number. 0=> add higher, value used returned
 * \param access access (OBIT_IO_ReadOnly, means do not create if it doesn't exist.
 * \param err Error stack, returns if not empty.
 * \return the new object, NULL on failure.
 */
ObitTableGBTVEGASSAMPLER* newObitTableGBTVEGASSAMPLERValue (gchar* name, ObitData *file, olong *ver,
 				  ObitIOAccess access,
  		    
		     ObitErr *err)
{
  ObitTableGBTVEGASSAMPLER* out=NULL;
  ObitTable *testTab=NULL;
  ObitTableDesc *desc=NULL;
  ObitTableList *list=NULL;
  ObitInfoList  *info=NULL;
  gboolean exist, optional;
  olong colNo, i, ncol, highVer;
  ObitIOCode retCode;
  gchar *tabType = "PORT";
  gchar *routine = "newObitTableGBTVEGASSAMPLERValue";

 /* error checks */
  g_assert(ObitErrIsA(err));
  if (err->error) return NULL;
  g_assert (ObitDataIsA(file));

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableGBTVEGASSAMPLERClassInit();

  /* Check if the table already exists */
  /* Get TableList */
  list = ((ObitData*)file)->tableList;
  info = ((ObitData*)file)->info;

  /* See if it already exists */
  exist = FALSE;
  if (*ver>0) { /* has to be specified */
    exist = ObitTableListGet(list, tabType, ver, &testTab, err);
    if (err->error) /* add traceback,return */
      Obit_traceback_val (err, routine,"", out);
  
    /* if readonly, it must exist to proceed */
    if ((access==OBIT_IO_ReadOnly) && !exist) return out;
    if (testTab!=NULL) { /* it exists, use it if is an ObitTableGBTVEGASSAMPLER */
      if (ObitTableGBTVEGASSAMPLERIsA(testTab)) { /* it is an ObitTableGBTVEGASSAMPLER */
	out = ObitTableRef(testTab);
      } else { /* needs conversion */
 	out = ObitTableGBTVEGASSAMPLERConvert(testTab);
	/* Update the TableList */
	ObitTableListPut(list, tabType, ver, (ObitTable*)out, err);
	if (err->error) Obit_traceback_val (err, routine,"", out);
      }
      testTab = ObitTableUnref(testTab); /* remove reference */
      return out; /* done */
    }
  } /* end of test for previously existing table */
  
  /* If access is ReadOnly make sure one exists */
  if (access==OBIT_IO_ReadOnly) { 
    highVer = ObitTableListGetHigh (list, "PORT");
    if (highVer<=0) return out;
  }
  
  /* create basal table */
  testTab = newObitDataTable ((ObitData*)file, access, tabType,
			       ver, err);
  if (err->error) Obit_traceback_val (err, routine,"", out);
  
  /* likely need to convert */
  if (ObitTableGBTVEGASSAMPLERIsA(testTab)) { 
    out = ObitTableRef(testTab);
  } else { /* needs conversion */
    out = ObitTableGBTVEGASSAMPLERConvert(testTab);
  }
  testTab = ObitTableUnref(testTab); /* remove reference */

  /* Update the TableList */
  ObitTableListPut(list, tabType, ver, (ObitTable*)out, err);
  if (err->error) /* add traceback,return */
    Obit_traceback_val (err, routine,"", out);

  /* if it previously existed merely return it */
  if (exist) return out; 

  /* set ClassInfo */
  out->ClassInfo = (gpointer)&myClassInfo;

  /* Set values */

  /* initialize descriptor */
  desc = out->myDesc;
  /* How many columns actually in table? */
  ncol = 9 ;
  desc->FieldName = g_malloc0((ncol+1)*sizeof(gchar*));
  desc->FieldUnit = g_malloc0((ncol+1)*sizeof(gchar*));
  desc->type      = g_malloc0((ncol+1)*sizeof(ObitInfoType));
  desc->dim       = g_malloc0((ncol+1)*sizeof(gint32*));
  for (i=0; i<ncol+1; i++) 
    desc->dim[i] = g_malloc0(MAXINFOELEMDIM*sizeof(gint32));

  desc->TableName = g_strdup(tabType);
  desc->sort[0] = 0;
  desc->sort[1] = 0;
  colNo = 0;

  /* Define Columns */
  desc->FieldName[colNo] = g_strdup("BANK_A  ");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_string;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("PORT_A  ");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_string;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("BANK_B  ");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_string;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("PORT_B  ");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_string;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("SUBBAND ");
  desc->FieldUnit[colNo] = g_strdup("");
  desc->type[colNo] = OBIT_short;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("CRVAL1  ");
  desc->FieldUnit[colNo] = g_strdup("HZ");
  desc->type[colNo] = OBIT_double;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("CDELT1  ");
  desc->FieldUnit[colNo] = g_strdup("HZ");
  desc->type[colNo] = OBIT_double;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  desc->FieldName[colNo] = g_strdup("FREQRES ");
  desc->FieldUnit[colNo] = g_strdup("HZ");
  desc->type[colNo] = OBIT_double;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  colNo++;
  optional = FALSE;
  if ((4 > 0) || (!optional)) {
    desc->FieldName[colNo] = g_strdup("DATATYPE");
    desc->FieldUnit[colNo] = g_strdup("");
    desc->type[colNo] = OBIT_string;
    for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
    desc->dim[colNo][0] = 4;
    colNo++;
  }
  /* Add _status column at end */
  desc->FieldName[colNo] = g_strdup("_status");
  desc->FieldUnit[colNo] = g_strdup("        ");
  desc->type[colNo] = OBIT_long;
  for (i=0; i<MAXINFOELEMDIM; i++) desc->dim[colNo][i] = 1;
  
  /* number of fields */
  desc->nfield = colNo + 1;

  /* initialize descriptor keywords */
  ObitTableGBTVEGASSAMPLERDumpKey (out, err);
 
  /* index table descriptor */
  ObitTableDescIndex (desc);

  /* Open and Close to fully instantiate */
  retCode = ObitTableGBTVEGASSAMPLEROpen(out, OBIT_IO_WriteOnly, err);
  if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
    Obit_traceback_val (err, routine, out->name, out);    
  
  retCode = ObitTableGBTVEGASSAMPLERClose(out, err);
  if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
    Obit_traceback_val (err, routine, out->name, out); 

  /* Force update of disk resident info */
  retCode = ObitIOUpdateTables (((ObitData*)file)->myIO, info, err);
  if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
    Obit_traceback_val (err, routine, out->name, out); 
  
 return out;
} /* end newObitTableGBTVEGASSAMPLERValue */

/**
 * Convert an ObitTable to an ObitTableGBTVEGASSAMPLER.
 * New object will have references to members of in.
 * \param in  The object to copy, will still exist afterwards 
 *            and should be Unrefed if not needed.
 * \return pointer to the new object.
 */
ObitTableGBTVEGASSAMPLER* ObitTableGBTVEGASSAMPLERConvert (ObitTable* in)
{
  ObitTableGBTVEGASSAMPLER *out;

  /* error check */
  g_assert(ObitTableIsA(in));

  /* create basic object */
  out = newObitTableGBTVEGASSAMPLER(in->name);

  /* Delete structures on new */
  out->info   = ObitInfoListUnref(out->info);
  out->thread = ObitThreadUnref(out->thread);
  out->myDesc = ObitTableDescUnref(out->myDesc);
  out->mySel  = ObitTableSelUnref(out->mySel);
  
  /* Reference members of in */
  
  out->info   = ObitInfoListRef(in->info);
  out->thread = ObitThreadRef(in->thread);
  out->myDesc = ObitTableDescRef(in->myDesc);
  out->mySel  = ObitTableSelRef(in->mySel);

  /* Remember who I am */
 out->tabType = g_strdup(in->tabType);
 out->tabVer  = in->tabVer;
  /* Secret reference to host */ 
 out->myHost  = in->myHost;

  return out;
} /* end ObitTableGBTVEGASSAMPLERConvert */


/**
 * Make a deep copy of input object.
 * Copies are made of complex members including disk files; these 
 * will be copied applying whatever selection is associated with the input.
 * Objects should be closed on input and will be closed on output.
 * In order for the disk file structures to be copied, the output file
 * must be sufficiently defined that it can be written.
 * The copy will be attempted but no errors will be logged until
 * both input and output have been successfully opened.
 * ObitInfoList and ObitThread members are only copied if the output object
 * didn't previously exist.
 * Parent class members are included but any derived class info is ignored.
 * \param in  The object to copy
 * \param out An existing object pointer for output or NULL if none exists.
 * \param err Error stack, returns if not empty.
 * \return pointer to the new object.
 */
ObitTableGBTVEGASSAMPLER* ObitTableGBTVEGASSAMPLERCopy (ObitTableGBTVEGASSAMPLER *in, ObitTableGBTVEGASSAMPLER *out, ObitErr *err)
{
  gchar *routine = "ObitTableGBTVEGASSAMPLERCopy";

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableGBTVEGASSAMPLERClassInit();

 /* error checks */
  g_assert(ObitErrIsA(err));
  if (err->error) return NULL;
  g_assert (ObitIsA(in, &myClassInfo));
  if (out) g_assert (ObitIsA(out, &myClassInfo));

  /* Use parent class to copy */
  out = (ObitTableGBTVEGASSAMPLER*)ObitTableCopy ((ObitTable*)in, (ObitTable*)out, err);
  if (err->error) /* add traceback,return */
    Obit_traceback_val (err, routine,in->name, out);

  /* Copy this class  info */
  out->crpix1 = in->crpix1;
  strncpy (out->polarize, in->polarize, MAXKEYCHARTABLEPORT );
  /* Update class specific info */
  ObitTableGBTVEGASSAMPLERUpdate (out, err);
    
  return out;
} /* end ObitTableGBTVEGASSAMPLERCopy */

/**
 * Initialize structures and open file.
 * The image descriptor is read if OBIT_IO_ReadOnly or 
 * OBIT_IO_ReadWrite and written to disk if opened OBIT_IO_WriteOnly.
 * After the file has been opened the member, buffer is initialized
 * for reading/storing the table unless member bufferSize is <0.
 * If the requested version ("Ver" in InfoList) is 0 then the highest
 * numbered table of the same type is opened on Read or Read/Write, 
 * or a new table is created on on Write.
 * The file etc. info should have been stored in the ObitInfoList:
 * \li "FileType" OBIT_long scalar = OBIT_IO_FITS 
 *               for file type (see class documentation for details).
 * \li "nRowPIO" OBIT_long scalar = Maximum number of table rows
 *               per transfer, this is the target size for Reads (may be 
 *               fewer) and is used to create buffers.
 * \param in Pointer to object to be opened.
 * \param access access (OBIT_IO_ReadOnly,OBIT_IO_ReadWrite,
 *               or OBIT_IO_WriteOnly).
 *               If OBIT_IO_WriteOnly any existing data in the output file
 *               will be lost.
 * \param err ObitErr for reporting errors.
 * \return return code, OBIT_IO_OK=> OK
 */
ObitIOCode ObitTableGBTVEGASSAMPLEROpen (ObitTableGBTVEGASSAMPLER *in, ObitIOAccess access, 
			  ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  gint32 dim[MAXINFOELEMDIM] = {1,1,1,1,1};
  olong nRowPIO;
  gchar *routine = "ObitTableGBTVEGASSAMPLEROpen";

  /* Class initialization if needed */
  if (!myClassInfo.initialized) ObitTableGBTVEGASSAMPLERClassInit();

  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA(in, &myClassInfo));

   /* Do one row at a time */
   nRowPIO = 1;
   ObitInfoListPut(in->info, "nRowPIO", OBIT_long, dim, (gconstpointer)&nRowPIO, err);
   if (err->error) /* add traceback,return */
     Obit_traceback_val (err, routine, in->name, retCode);
   
   /* use parent class open */
   retCode = ObitTableOpen ((ObitTable*)in, access, err);
   if ((retCode!=OBIT_IO_OK) || (err->error)) /* add traceback,return */
     Obit_traceback_val (err, routine, in->name, retCode);
   
   /* Update class specific info */
   ObitTableGBTVEGASSAMPLERUpdate (in, err);
   
   return retCode;
} /* end ObitTableGBTVEGASSAMPLEROpen */

/**
 * Read a table row and return an easily digested version.
 * Scalar values are copied but for array values, pointers 
 * into the data array are returned.
 * \param in       Table to read
 * \param iPORTRow   Row number, -1 -> next
 * \param row      Table Row structure to receive data
 * \param err ObitErr for reporting errors.
 * \return return code, OBIT_IO_OK=> OK
 */
ObitIOCode 
ObitTableGBTVEGASSAMPLERReadRow  (ObitTableGBTVEGASSAMPLER *in, olong iPORTRow, ObitTableGBTVEGASSAMPLERRow *row,
		     ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  odouble   *dRow;
  oint      *iRow;
  gshort    *siRow;
  ollong    *llRow;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;
  gchar *routine = "ObitTableGBTVEGASSAMPLERReadRow";
  
  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA(in, &myClassInfo));

  if (in->myStatus == OBIT_Inactive) {
    Obit_log_error(err, OBIT_Error,
		   "ObitTableGBTVEGASSAMPLER Table is inactive for  %s ", in->name);
    return retCode;
 }

  /* read row iPORTRow */
  retCode = ObitTableRead ((ObitTable*)in, iPORTRow, NULL,  err);
  if (err->error) 
    Obit_traceback_val (err, routine, in->name, retCode);

  /* Typed pointers to row of data */  
  dRow  = (odouble*)in->buffer;
  iRow  = (oint*)in->buffer;
  siRow = (gshort*)in->buffer;
  llRow = (ollong*)in->buffer;
  fRow  = (ofloat*)in->buffer;
  cRow  = (gchar*)in->buffer;
  lRow  = (gboolean*)in->buffer;
  bRow  = (guint8*)in->buffer;
  
  /* Copy scalar fields, for arrays only set pointer*/
  row->bank_a = cRow[in->bank_aOff];
  row->port_a = cRow[in->port_aOff];
  row->bank_b = cRow[in->bank_bOff];
  row->port_b = cRow[in->port_bOff];
  row->subband = siRow[in->subbandOff];
  row->crval1 = dRow[in->crval1Off];
  row->cdelt1 = dRow[in->cdelt1Off];
  row->freqres = dRow[in->freqresOff];
  row->datatype = cRow + in->datatypeOff;
  row->status = iRow[in->myDesc->statusOff];

  return retCode;
} /*  end ObitTableGBTVEGASSAMPLERReadRow */

/**
 * Attach an ObitTableRow to the buffer of an ObitTable.
 * This is only useful prior to filling a row structure in preparation .
 * for a WriteRow operation.  Array members of the Row structure are .
 * pointers to independently allocated memory, this routine allows using .
 * the table IO buffer instead of allocating yet more memory..
 * This routine need only be called once to initialize a Row structure for write..
 * \param in  Table with buffer to be written 
 * \param row Table Row structure to attach 
 * \param err ObitErr for reporting errors.
 */
void 
ObitTableGBTVEGASSAMPLERSetRow  (ObitTableGBTVEGASSAMPLER *in, ObitTableGBTVEGASSAMPLERRow *row,
		     ObitErr *err)
{
  odouble   *dRow;
  oint      *iRow;
  gshort    *siRow;
  ollong    *llRow;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;
  
  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return;
  g_assert (ObitIsA(in, &myClassInfo));
  g_assert (ObitIsA(row, &myRowClassInfo));

  if (in->myStatus == OBIT_Inactive) {
    Obit_log_error(err, OBIT_Error,
		   "PORT Table is inactive for  %s ", in->name);
    return;
 }

  /* Typed pointers to row of data */  
  dRow  = (odouble*)in->buffer;
  iRow  = (oint*)in->buffer;
  siRow = (gshort*)in->buffer;
  llRow = (ollong*)in->buffer;
  fRow  = (ofloat*)in->buffer;
  cRow  = (gchar*)in->buffer;
  lRow  = (gboolean*)in->buffer;
  bRow  = (guint8*)in->buffer;
  
  /* Set row pointers to buffer */
  row->datatype = cRow + in->datatypeOff;

} /*  end ObitTableGBTVEGASSAMPLERSetRow */

/**
 * Write a table row.
 * Before calling this routine, the row structure needs to be initialized
 * and filled with data. The array members of the row structure are  
 * pointers to independently allocated memory.  These pointers can be set to the 
 * correct table buffer locations using ObitTableGBTVEGASSAMPLERSetRow  
 * \param in       Table to read
 * \param iPORTRow   Row number, -1 -> next
 * \param row      Table Row structure containing data
 * \param err ObitErr for reporting errors.
 * \return return code, OBIT_IO_OK=> OK
 */
ObitIOCode 
ObitTableGBTVEGASSAMPLERWriteRow  (ObitTableGBTVEGASSAMPLER *in, olong iPORTRow, ObitTableGBTVEGASSAMPLERRow *row,
		      ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  gshort    *siRow;
  ollong    *llRow;
  odouble   *dRow;
  oint      *iRow, i;
  ofloat    *fRow;
  gchar     *cRow;
  gboolean  *lRow;
  guint8    *bRow;
  gchar *routine = "ObitTableGBTVEGASSAMPLERWriteRow";
  

  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA(in, &myClassInfo));

  if (in->myStatus == OBIT_Inactive) {
    Obit_log_error(err, OBIT_Error,
		   "ObitTableGBTVEGASSAMPLER Table is inactive for %s ", in->name);
    return retCode;
 }

  /* Typed pointers to row of data */  
  dRow  = (odouble*)in->buffer;
  siRow = (gshort*)in->buffer;
  llRow = (ollong*)in->buffer;
  iRow  = (oint*)in->buffer;
  fRow  = (ofloat*)in->buffer;
  cRow  = (gchar*)in->buffer;
  lRow  = (gboolean*)in->buffer;
  bRow  = (guint8*)in->buffer;
  
  /* Make full copy of all data */
  cRow[in->bank_aOff] = row->bank_a;
  cRow[in->port_aOff] = row->port_a;
  cRow[in->bank_bOff] = row->bank_b;
  cRow[in->port_bOff] = row->port_b;
  siRow[in->subbandOff] = row->subband;
  dRow[in->crval1Off] = row->crval1;
  dRow[in->cdelt1Off] = row->cdelt1;
  dRow[in->freqresOff] = row->freqres;
  if (in->datatypeCol >= 0) { 
    for (i=0; i<in->myDesc->repeat[in->datatypeCol]; i++) 
      cRow[in->datatypeOff+i] = row->datatype[i];
  } 

  /* copy status */
  iRow[in->myDesc->statusOff] = row->status;
   
  /* Write one row */
  in->myDesc->numRowBuff = 1;
 
  /* Write row iPORTRow */
  retCode = ObitTableWrite ((ObitTable*)in, iPORTRow, NULL,  err);
  if (err->error) 
    Obit_traceback_val (err, routine,in->name, retCode);

  return retCode;
} /*  end ObitTableGBTVEGASSAMPLERWriteRow */

/**
 * Shutdown I/O.
 * \param in Pointer to object to be closed.
 * \param err ObitErr for reporting errors.
 * \return error code, OBIT_IO_OK=> OK
 */
ObitIOCode ObitTableGBTVEGASSAMPLERClose (ObitTableGBTVEGASSAMPLER *in, ObitErr *err)
{
  ObitIOCode retCode = OBIT_IO_SpecErr;
  gchar *routine = "ObitTableGBTVEGASSAMPLERClose";

  /* error checks */
  g_assert (ObitErrIsA(err));
  if (err->error) return retCode;
  g_assert (ObitIsA((Obit*)in, &myClassInfo));
  /* Something going on? */
  if (in->myStatus == OBIT_Inactive) return OBIT_IO_OK;

  /* Update keywords on descriptor if not ReadOnly*/
  if (in->myDesc->access != OBIT_IO_ReadOnly) 
    ObitTableGBTVEGASSAMPLERDumpKey (in, err);
  if (err->error) 
    Obit_traceback_val (err, routine, in->name, retCode);

  /* Close */
  retCode = ObitTableClose ((ObitTable*)in, err);
  if (err->error) 
    Obit_traceback_val (err, routine, in->name, retCode);

  return retCode;
} /* end ObitTableGBTVEGASSAMPLERClose */

/*---------------Private functions--------------------------*/
/*----------------  ObitTableGBTVEGASSAMPLER Row  ----------------------*/
/**
 * Creates empty member objects, initialize reference count.
 * Parent classes portions are (recursively) initialized first
 * \param inn Pointer to the object to initialize.
 */
void ObitTableGBTVEGASSAMPLERRowInit  (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableGBTVEGASSAMPLERRow *in = inn;

  /* error checks */
  g_assert (in != NULL);

  /* recursively initialize parent class members */
  ParentClass = (ObitClassInfo*)(myRowClassInfo.ParentClass);
  if ((ParentClass!=NULL) && ( ParentClass->ObitInit!=NULL)) 
    ParentClass->ObitInit (inn);

  /* set members in this class */
  /* Set array members to NULL */
  in->datatype = NULL;

} /* end ObitTableGBTVEGASSAMPLERRowInit */

/**
 * Deallocates member objects.
 * Does (recursive) deallocation of parent class members.
 * For some reason this wasn't build into the GType class.
 * \param  inn Pointer to the object to deallocate.
 *           Actually it should be an ObitTableGBTVEGASSAMPLERRow* cast to an Obit*.
 */
void ObitTableGBTVEGASSAMPLERRowClear (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableGBTVEGASSAMPLERRow *in = inn;

  /* error checks */
  g_assert (ObitIsA(in, &myRowClassInfo));

  /* delete this class members */
  /* Do not free data array pointers as they were not malloced */
  
  /* unlink parent class members */
  ParentClass = (ObitClassInfo*)(myRowClassInfo.ParentClass);
  /* delete parent class members */
  if ((ParentClass!=NULL) && ( ParentClass->ObitClear!=NULL)) 
    ParentClass->ObitClear (inn);
  
} /* end ObitTableGBTVEGASSAMPLERRowClear */

/**
 * Initialize global ClassInfo Structure.
 */
void ObitTableGBTVEGASSAMPLERRowClassInit (void)
{
  if (myRowClassInfo.initialized) return;  /* only once */
  
  /* Set name and parent for this class */
  myRowClassInfo.ClassName   = g_strdup(myRowClassName);
  myRowClassInfo.ParentClass = ObitParentGetRowClass();

  /* Set function pointers */
  ObitTableGBTVEGASSAMPLERRowClassInfoDefFn ((gpointer)&myRowClassInfo);
 
  myRowClassInfo.initialized = TRUE; /* Now initialized */
 
} /* end ObitTableGBTVEGASSAMPLERRowClassInit */

/**
 * Initialize global ClassInfo Function pointers.
 */
static void ObitTableGBTVEGASSAMPLERRowClassInfoDefFn (gpointer inClass)
{
  ObitTableGBTVEGASSAMPLERRowClassInfo *theClass = (ObitTableGBTVEGASSAMPLERRowClassInfo*)inClass;
  ObitClassInfo *ParentClass = (ObitClassInfo*)myRowClassInfo.ParentClass;

  if (theClass->initialized) return;  /* only once */

  /* Check type of inClass */
  g_assert (ObitInfoIsA(inClass, (ObitClassInfo*)&myRowClassInfo));

  /* Initialize (recursively) parent class first */
  if ((ParentClass!=NULL) && 
      (ParentClass->ObitClassInfoDefFn!=NULL))
    ParentClass->ObitClassInfoDefFn(theClass);

  /* function pointers defined or overloaded this class */
  theClass->ObitClassInit = (ObitClassInitFP)ObitTableGBTVEGASSAMPLERRowClassInit;
  theClass->ObitClassInfoDefFn = (ObitClassInfoDefFnFP)ObitTableGBTVEGASSAMPLERRowClassInfoDefFn;
  theClass->ObitGetClass  = (ObitGetClassFP)ObitTableGBTVEGASSAMPLERRowGetClass;
  theClass->newObit         = NULL;
  theClass->newObitTableRow = (newObitTableRowFP)newObitTableGBTVEGASSAMPLERRow;
  theClass->ObitCopy        = NULL;
  theClass->ObitClone       = NULL;
  theClass->ObitClear       = (ObitClearFP)ObitTableGBTVEGASSAMPLERRowClear;
  theClass->ObitInit        = (ObitInitFP)ObitTableGBTVEGASSAMPLERRowInit;

} /* end ObitTableGBTVEGASSAMPLERRowClassDefFn */

/*------------------  ObitTableGBTVEGASSAMPLER  ------------------------*/

/**
 * Creates empty member objects, initialize reference count.
 * Parent classes portions are (recursively) initialized first
 * \param inn Pointer to the object to initialize.
 */
void ObitTableGBTVEGASSAMPLERInit  (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableGBTVEGASSAMPLER *in = inn;

  /* error checks */
  g_assert (in != NULL);

  /* recursively initialize parent class members */
  ParentClass = (ObitClassInfo*)(myClassInfo.ParentClass);
  if ((ParentClass!=NULL) && ( ParentClass->ObitInit!=NULL)) 
    ParentClass->ObitInit (inn);

  /* set members in this class */

} /* end ObitTableGBTVEGASSAMPLERInit */

/**
 * Deallocates member objects.
 * Does (recursive) deallocation of parent class members.
 * For some reason this wasn't build into the GType class.
 * \param  inn Pointer to the object to deallocate.
 *           Actually it should be an ObitTableGBTVEGASSAMPLER* cast to an Obit*.
 */
void ObitTableGBTVEGASSAMPLERClear (gpointer inn)
{
  ObitClassInfo *ParentClass;
  ObitTableGBTVEGASSAMPLER *in = inn;

  /* error checks */
  g_assert (ObitIsA(in, &myClassInfo));

  /* delete this class members */
  
  /* unlink parent class members */
  ParentClass = (ObitClassInfo*)(myClassInfo.ParentClass);
  /* delete parent class members */
  if ((ParentClass!=NULL) && ( ParentClass->ObitClear!=NULL)) 
    ParentClass->ObitClear (inn);
  
} /* end ObitTableGBTVEGASSAMPLERClear */

/**
 * Initialize global ClassInfo Structure.
 */
void ObitTableGBTVEGASSAMPLERClassInit (void)
{
  if (myClassInfo.initialized) return;  /* only once */
  
  /* Set name and parent for this class */
  myClassInfo.ClassName   = g_strdup(myClassName);
  myClassInfo.ParentClass = ObitParentGetClass();

  /* Set function pointers */
  ObitTableGBTVEGASSAMPLERClassInfoDefFn ((gpointer)&myClassInfo);
 
  myClassInfo.initialized = TRUE; /* Now initialized */
 
} /* end ObitTableGBTVEGASSAMPLERClassInit */

/**
 * Initialize global ClassInfo Function pointers.
 */
static void ObitTableGBTVEGASSAMPLERClassInfoDefFn (gpointer inClass)
{
  ObitTableGBTVEGASSAMPLERClassInfo *theClass = (ObitTableGBTVEGASSAMPLERClassInfo*)inClass;
  ObitClassInfo *ParentClass = (ObitClassInfo*)myClassInfo.ParentClass;

  if (theClass->initialized) return;  /* only once */

  /* Check type of inClass */
  g_assert (ObitInfoIsA(inClass, (ObitClassInfo*)&myClassInfo));

  /* Initialize (recursively) parent class first */
  if ((ParentClass!=NULL) && 
      (ParentClass->ObitClassInfoDefFn!=NULL))
    ParentClass->ObitClassInfoDefFn(theClass);

  /* function pointers defined or overloaded this class */
  theClass->ObitClassInit = (ObitClassInitFP)ObitTableGBTVEGASSAMPLERClassInit;
  theClass->ObitClassInfoDefFn = (ObitClassInfoDefFnFP)ObitTableGBTVEGASSAMPLERClassInfoDefFn;
  theClass->ObitGetClass  = (ObitGetClassFP)ObitTableGBTVEGASSAMPLERGetClass;
  theClass->newObit       = (newObitFP)newObitTableGBTVEGASSAMPLER;
  theClass->ObitCopy      = (ObitCopyFP)ObitTableGBTVEGASSAMPLERCopy;
  theClass->ObitClone     = (ObitCloneFP)ObitTableClone;
  theClass->ObitClear     = (ObitClearFP)ObitTableGBTVEGASSAMPLERClear;
  theClass->ObitInit      = (ObitInitFP)ObitTableGBTVEGASSAMPLERInit;
  theClass->ObitTableConvert = (ObitTableConvertFP)ObitTableGBTVEGASSAMPLERConvert;
  theClass->ObitTableOpen    = (ObitTableOpenFP)ObitTableGBTVEGASSAMPLEROpen;
  theClass->ObitTableClose   = (ObitTableCloseFP)ObitTableGBTVEGASSAMPLERClose;
  theClass->ObitTableRead    = (ObitTableReadFP)ObitTableRead;
  theClass->ObitTableReadSelect = 
    (ObitTableReadSelectFP)ObitTableReadSelect;
  theClass->ObitTableWrite = (ObitTableWriteFP)ObitTableWrite;
  theClass->ObitTableReadRow = 
    (ObitTableReadRowFP)ObitTableGBTVEGASSAMPLERReadRow;
  theClass->ObitTableWriteRow = 
    (ObitTableWriteRowFP)ObitTableGBTVEGASSAMPLERWriteRow;

} /* end ObitTableGBTVEGASSAMPLERClassDefFn */

/**
 * Get table specific information from the infolist or descriptor
 * \param info Table to update
 * \param err  ObitErr for reporting errors.
 */
static void ObitTableGBTVEGASSAMPLERUpdate (ObitTableGBTVEGASSAMPLER *in, ObitErr *err)
{
  olong i;
  ObitInfoType type;
  gint32 dim[MAXINFOELEMDIM];
  ObitTableDesc *desc;
   union ObitInfoListEquiv InfoReal; 

 /* error checks */
   g_assert(ObitErrIsA(err));
  if (err->error) return;
  g_assert (ObitIsA(in, &myClassInfo));

  /* Get Keywords */
   /* crpix1 */
  if (!ObitInfoListGet(in->myDesc->info, "CRPIX1", &type, (gint32*)&dim, 
		       (gpointer)&InfoReal, err)) return;
  if (type==OBIT_double) in->crpix1 = InfoReal.dbl;
  if (type==OBIT_float)  in->crpix1 = InfoReal.flt;
   /* polarize */
  if (!ObitInfoListGet(in->myDesc->info, "POLARIZE", &type, (gint32*)&dim, 
		       (gpointer)&in->polarize, err)) return;

  /* initialize column numbers/offsets */
  in->bank_aOff = -1;
  in->bank_aCol = -1;
  in->port_aOff = -1;
  in->port_aCol = -1;
  in->bank_bOff = -1;
  in->bank_bCol = -1;
  in->port_bOff = -1;
  in->port_bCol = -1;
  in->datatypeOff = -1;
  in->datatypeCol = -1;
  in->subbandOff = -1;
  in->subbandCol = -1;
  in->crval1Off = -1;
  in->crval1Col = -1;
  in->cdelt1Off = -1;
  in->cdelt1Col = -1;
  in->freqresOff = -1;
  in->freqresCol = -1;
  /* Find columns and set offsets */
  desc = in->myDesc;
  if (desc->FieldName) {
    for (i=0; i<desc->nfield; i++) {
      if (!strncmp (desc->FieldName[i], "BANK_A  ", 8)) {
	 in->bank_aOff = desc->offset[i];
 	 in->bank_aCol = i;
      }
      if (!strncmp (desc->FieldName[i], "PORT_A  ", 8)) {
	 in->port_aOff = desc->offset[i];
 	 in->port_aCol = i;
      }
      if (!strncmp (desc->FieldName[i], "BANK_B  ", 8)) {
	 in->bank_bOff = desc->offset[i];
 	 in->bank_bCol = i;
      }
      if (!strncmp (desc->FieldName[i], "PORT_B  ", 8)) {
	 in->port_bOff = desc->offset[i];
 	 in->port_bCol = i;
      }
      if (!strncmp (desc->FieldName[i], "DATATYPE", 8)) {
	 in->datatypeOff = desc->offset[i];
 	 in->datatypeCol = i;
      }
      if (!strncmp (desc->FieldName[i], "SUBBAND ", 8)) {
	 in->subbandOff = desc->offset[i];
 	 in->subbandCol = i;
      }
      if (!strncmp (desc->FieldName[i], "CRVAL1  ", 8)) {
	 in->crval1Off = desc->offset[i];
 	 in->crval1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "CDELT1  ", 8)) {
	 in->cdelt1Off = desc->offset[i];
 	 in->cdelt1Col = i;
      }
      if (!strncmp (desc->FieldName[i], "FREQRES ", 8)) {
	 in->freqresOff = desc->offset[i];
 	 in->freqresCol = i;
      }
     }
  }

  Obit_return_if_fail((in->bank_aOff > -1), err,
       "ObitTablePORTUpdate: Could not find column bank_a");
  Obit_return_if_fail((in->port_aOff > -1), err,
       "ObitTablePORTUpdate: Could not find column port_a");
  Obit_return_if_fail((in->bank_bOff > -1), err,
       "ObitTablePORTUpdate: Could not find column bank_b");
  Obit_return_if_fail((in->port_bOff > -1), err,
       "ObitTablePORTUpdate: Could not find column port_b");
  Obit_return_if_fail((in->datatypeOff > -1), err,
       "ObitTablePORTUpdate: Could not find column datatype");
  Obit_return_if_fail((in->subbandOff > -1), err,
       "ObitTablePORTUpdate: Could not find column subband");
  Obit_return_if_fail((in->crval1Off > -1), err,
       "ObitTablePORTUpdate: Could not find column crval1");
  Obit_return_if_fail((in->cdelt1Off > -1), err,
       "ObitTablePORTUpdate: Could not find column cdelt1");
} /* end ObitTableGBTVEGASSAMPLERUpdate */

/**
 * Copy table specific (keyword) information  to infolist.
 * \param info Table to update
 * \param err  ObitErr for reporting errors.
 */
static void ObitTableGBTVEGASSAMPLERDumpKey (ObitTableGBTVEGASSAMPLER *in, ObitErr *err)
{
  ObitInfoList *info=NULL;
  ObitInfoType type;
  gint32 dim[MAXINFOELEMDIM] = {1,1,1,1,1};

 /* error checks */
   g_assert(ObitErrIsA(err));
  if (err->error) return;
  g_assert (ObitIsA(in, &myClassInfo));

  /* Set Keywords */
  if (in->myIO!=NULL) info = ((ObitTableDesc*)(in->myIO->myDesc))->info;
  else info = in->myDesc->info;
  /* crpix1 */
  type  = OBIT_float;
  dim[0] = 1;
  ObitInfoListAlwaysPut(info, "CRPIX1", type, (gint32*)&dim, 
		  (gpointer)&in->crpix1);
  /* polarize */
  type  = OBIT_string;
  dim[0] = MAXKEYCHARTABLEPORT;
  ObitInfoListAlwaysPut(info, "POLARIZE", type, (gint32*)&dim, 
		  (gpointer)&in->polarize);
   
} /* end ObitTableGBTVEGASSAMPLERDumpKey */
