/* $Id$   */
/* DO NOT EDIT - file generated by ObitTables.pl                      */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2013                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                         */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
/*  Define the basic components of the ObitTableIDI_GAIN_CURVE  structure          */
/*  This is intended to be included in a class structure definition   */
/**
 * \file ObitTableIDI_GAIN_CURVEDef.h
 * ObitTableIDI_GAIN_CURVE structure members for derived classes.
 */
#include "ObitTableDef.h"  /* Parent class definitions */
/** Table format revision number */
oint  tabrev;
/** [OPTIONAL] The number of polarizations */
oint  numPol;
/** [OPTIONAL] Number of frequency bands */
oint  no_band;
/** The number of tabulated terms */
oint  numTabs;
/** Number of frequency channels */
oint  no_chan;
/** Number of Stokes parameters */
oint  no_stkd;
/** First Stokes parameter */
oint  stk_1;
/** Reference frequency (Hz) */
odouble  ref_freq;
/** Channel bandwidth (Hz) */
odouble  chan_bw;
/** Reference frequency bin */
oint  ref_pixl;
/** Observation project code */
gchar  obscode[MAXKEYCHARTABLEIDI_GAIN_CURVE];
/** Column offset for Antenna number in table record */
olong  antNoOff;
/** Physical column number for Antenna number in table record */
olong  antNoCol;
/** Column offset for Array number. in table record */
olong  ArrayOff;
/** Physical column number for Array number. in table record */
olong  ArrayCol;
/** Column offset for Frequency ID number for row, this is a random parameter in the uv data in table record */
olong  fqidOff;
/** Physical column number for Frequency ID number for row, this is a random parameter in the uv data in table record */
olong  fqidCol;
/** Column offset for Gain curve type for poln # 1 in table record */
olong  type1Off;
/** Physical column number for Gain curve type for poln # 1 in table record */
olong  type1Col;
/** Column offset for Number of terms for poln # 1 in table record */
olong  nterm1Off;
/** Physical column number for Number of terms for poln # 1 in table record */
olong  nterm1Col;
/** Column offset for X value types for poln # 1 in table record */
olong  x_typ1Off;
/** Physical column number for X value types for poln # 1 in table record */
olong  x_typ1Col;
/** Column offset for Y value types for poln # 1 in table record */
olong  y_typ1Off;
/** Physical column number for Y value types for poln # 1 in table record */
olong  y_typ1Col;
/** Column offset for X values for poln # 1 in table record */
olong  x_val1Off;
/** Physical column number for X values for poln # 1 in table record */
olong  x_val1Col;
/** Column offset for Y values for poln # 1 in table record */
olong  y_val1Off;
/** Physical column number for Y values for poln # 1 in table record */
olong  y_val1Col;
/** Column offset for for poln # 1 in table record */
olong  gain1Off;
/** Physical column number for for poln # 1 in table record */
olong  gain1Col;
/** Column offset for for poln # 1 in table record */
olong  sens1Off;
/** Physical column number for for poln # 1 in table record */
olong  sens1Col;
/** Column offset for Gain curve type for poln # 2 in table record */
olong  type2Off;
/** Physical column number for Gain curve type for poln # 2 in table record */
olong  type2Col;
/** Column offset for Number of terms for poln # 2 in table record */
olong  nterm2Off;
/** Physical column number for Number of terms for poln # 2 in table record */
olong  nterm2Col;
/** Column offset for X value types for poln # 2 in table record */
olong  x_typ2Off;
/** Physical column number for X value types for poln # 2 in table record */
olong  x_typ2Col;
/** Column offset for Y value types for poln # 2 in table record */
olong  y_typ2Off;
/** Physical column number for Y value types for poln # 2 in table record */
olong  y_typ2Col;
/** Column offset for X values for poln # 2 in table record */
olong  x_val2Off;
/** Physical column number for X values for poln # 2 in table record */
olong  x_val2Col;
/** Column offset for Y values for poln # 2 in table record */
olong  y_val2Off;
/** Physical column number for Y values for poln # 2 in table record */
olong  y_val2Col;
/** Column offset for for poln # 2 in table record */
olong  gain2Off;
/** Physical column number for for poln # 2 in table record */
olong  gain2Col;
/** Column offset for for poln # 2 in table record */
olong  sens2Off;
/** Physical column number for for poln # 2 in table record */
olong  sens2Col;
