/* $Id$   */
/* DO NOT EDIT - file generated by ObitTables.pl                      */
/*--------------------------------------------------------------------*/
/*;  Copyright (C)  2008                                              */
/*;  Associated Universities, Inc. Washington DC, USA.                */
/*;                                                                   */
/*;  This program is free software; you can redistribute it and/or    */
/*;  modify it under the terms of the GNU General Public License as   */
/*;  published by the Free Software Foundation; either version 2 of   */
/*;  the License, or (at your option) any later version.              */
/*;                                                                   */
/*;  This program is distributed in the hope that it will be useful,  */
/*;  but WITHOUT ANY WARRANTY; without even the implied warranty of   */
/*;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    */
/*;  GNU General Public License for more details.                     */
/*;                                                                   */
/*;  You should have received a copy of the GNU General Public        */
/*;  License along with this program; if not, write to the Free       */
/*;  Software Foundation, Inc., 675 Massachusetts Ave, Cambridge,     */
/*;  MA 02139, USA.                                                   */
/*;                                                                   */
/*;Correspondence about this software should be addressed as follows: */
/*;         Internet email: bcotton@nrao.edu.                        */
/*;         Postal address: William Cotton                            */
/*;                         National Radio Astronomy Observatory      */
/*;                         520 Edgemont Road                         */
/*;                         Charlottesville, VA 22903-2475 USA        */
/*--------------------------------------------------------------------*/
/*  Define the basic components of the ObitTableRow structure       */
/*  This is intended to be included in a class structure definition   */
/**
 * \file ObitTableCLRowDef.h
 * ObitTableCLRow structure members for derived classes.
 */
#include "ObitTableRowDef.h"  /* Parent class definitions */
/** The center time of the solution */
gdouble  Time;
/** Solution interval. */
gfloat  TimeI;
/** Source Identifier number */
oint  SourID;
/** Antenna number */
oint  antNo;
/** Subarray number. */
oint  SubA;
/** Frequency ID */
oint  FreqID;
/** Ionospheric Faraday Rotation */
gfloat  IFR;
/** Atmospheric delay */
gfloat  atmos;
/** Time derivative of ATMOS */
gfloat  Datmos;
/** Geometric delay polynomial series at TIME */
gdouble*  GeoDelay;
/** Doppler offset for each IF */
gfloat*  DopplerOff;
/** Multiband delay poln # 1 */
gfloat  MBDelay1;
/** "Clock" epoch error */
gfloat  clock1;
/** Time derivative of CLOCK */
gfloat  Dclock1;
/** Dispersive delay (sec at wavelength = 1m)for Poln # 1 */
gfloat  dispers1;
/** Time derivative of DISPfor Poln # 1 */
gfloat  Ddispers1;
/** Real (gain Poln # 1 ) */
gfloat*  Real1;
/** Imaginary (gain Poln # 1) */
gfloat*  Imag1;
/** Residual fringe rate  Poln # 1 */
gfloat*  Rate1;
/** Residual group delay Poln # 1 */
gfloat*  Delay1;
/** Weight of soln. Poln # 1 */
gfloat*  Weight1;
/** Reference antenna Poln # 1 */
oint*  RefAnt1;
/** Multiband delay poln # 2 */
gfloat  MBDelay2;
/** "Clock" epoch error */
gfloat  clock2;
/** Time derivative of CLOCK */
gfloat  Dclock2;
/** Dispersive delay (sec at wavelength = 1m)for Poln # 2 */
gfloat  dispers2;
/** Time derivative of DISPfor Poln # 2 */
gfloat  Ddispers2;
/** Real (gain Poln # 2 ) */
gfloat*  Real2;
/** Imaginary (gain Poln # 2) */
gfloat*  Imag2;
/** Residual fringe rate  Poln # 2 */
gfloat*  Rate2;
/** Residual group delay Poln # 2 */
gfloat*  Delay2;
/** Weight of soln. Poln # 2 */
gfloat*  Weight2;
/** Reference antenna Poln # 2 */
oint*  RefAnt2;
/** status 0=normal, 1=modified, -1=flagged */
olong  status;
